### ISSUE TITLE
Client crash: Outdated API?

### ISSUE THREAD

**Issue by gdude2002** [Flemmli97/Flan#10]
#### Issue (The better the description the better i can solve the issue):

Looks like Flan's using an outdated API. Seems like that to me, at least.

#### Steps to reproduce:

Install and start up.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.3
- Fabric: API 0.24.3+build.414-1.16
- Flan:1.16.2-1.1.0

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE): 

The log isn't directly related to Flan, but it is mentioned in the traceback.

[message.txt](https://github.com/Flemmli97/Flan/files/5467048/message.txt)

**Comment by Flemmli97** [comment]
update fabric launcher. its a fabric api issue. it needs a higher launcher version
