### ISSUE TITLE
Expanded Storage not protected under claim

### ISSUE THREAD

**Issue by itsdinkd** [Flemmli97/Flan#103]
1.6.2 / Fabric / 1.17.1 

As title suggests, expanded storage chests / barrels are not protected inside claims.

Also, please release 1.6.3

**Comment by elhertz** [comment]
ExpandedStorage's dev added support for Flan
https://github.com/NinjaPhenix/container-library/commit/335aa4024d061d2b89412aac03767ed84decf75c
