### ISSUE TITLE
[1.18] Flan Crashes while Loading world

### ISSUE THREAD

**Issue by Carterpersall** [Flemmli97/Flan#105]
#### Issue (The better the description the better I can solve the issue):
I manually updated the mod to 1.18 to see if it works and the game crashes whenever I enter a world. It seems to be /flan/config/ConfigHandler.java:38 that is causing the issue. Tried figuring it out myself but I'm a javascript noob.

#### Steps to reproduce:
1. Open World
2. Game Crashes
3. ...
4. Profit

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.18
- Forge: If forge
- Fabric(API): 0.43.1+1.18
- Flan: 1.17.1-1.6.3

#### Other Mods (If you think it might be cause of an incompability. Adding a link + the used version will help greatly):
Tried both with and without mods with no change in behavior

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE):
[https://crashy.net/pE1tzjDSCi4PwZ4xM3Xa](url)

**Comment by Flemmli97** [comment]
wait for 1.18 version. any kind of other tries you are on your own

**Comment by Carterpersall** [comment]
Just making you aware of what I've found to hopefully help out. Loving the great work you've done on this mod!
