### ISSUE TITLE
Please mix into World#canPlayerModifyAt to include a claim check

### ISSUE THREAD

**Issue by Technici4n** [Flemmli97/Flan#106]
This will
- fix MI wrenches ignoring claims,
- allow other mods to add claim compat in a trivial manner.

**Comment by Technici4n** [comment]
(Don't literally `@Override` it as other mods might edit it too :P)

**Comment by Flemmli97** [comment]
reason why i didnt is cause that place is not specific enough for a check. vanilla calls it at various places and you dont know what item is being used or if its a left or right click.
there is an api that other mods can use to check for claim permissions

**Comment by Technici4n** [comment]
Yes but I don't want to depend on every single claim mod. Another solution is to move your UseItemCallback listener to an earlier event phase to at least cancel all interactions happening in the default phase (which is the case for MI wrenches).

**Comment by Flemmli97** [comment]
hmm the place of the check isnt actually the issue i see. 
its cause i have a map of item -> permission and only items in that map are considered
i could make it so modpack maker can additionally specify a mapping via config though but otherwise see no better way to achieve this

**Comment by Technici4n** [comment]
I guess you could check for the `c:wrenches` tag that defines wrench functionality?

**Comment by Flemmli97** [comment]
btw in what way are they ignoring claims? i tested the wrenches on machines, pistons or even plain blocks and the claims blocked them

**Comment by Technici4n** [comment]
You should check shift + right-clicking an MI pipe with the MI wrench, some people reported to me that it bypassed claims on aof5 but I haven't checked myself.

**Comment by Technici4n** [comment]
You should also check AE2's wrench, it might have the same issue. (Might also be dependent on mod load order, so I'd suggest testing in dev which makes it random).

**Comment by Flemmli97** [comment]
mi wrench is just a client desync. ae2 does break the blocks. not too sure how to solve the client desync though cause sending a blockupdate packet isnt doing anything.
i will prob just leave that like it since it doesnt actually have a big impact

**Comment by Technici4n** [comment]
Did you move your event listener to an earlier phase? That should help. (addPhaseOrdering iirc)

**Comment by Flemmli97** [comment]
ae2 is handled. mi will just have the desync if cables are shift right clicked with a wrench

**Comment by Technici4n** [comment]
Sounds reasonable, thanks for taking the time to go through this issue.
