### ISSUE TITLE
Claims not working below 0

### ISSUE THREAD

**Issue by Jlibb** [Flemmli97/Flan#108]
#### Issue (The better the description the better i can solve the issue):
Same as in issue #60
Claim not working below Y-depth 0

#### Steps to reproduce:
Only running on the server. The world was generated before the mod was added.
Set the defaultClaimDepth on a high enough value (tried 500, 200, 100). Reloaded the configs, also tried restarting the server.
Create a claim, and check for the claim at Y levels below zero (for example with a stick).

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.18
- Fabric(API): fabric-api-0.44.0+1.18
- Flan: flan-1.18-1.6.4

#### Other Mods (If you think it might be cause of an incompability. Adding a link + the used version will help greatly):

Running a modpack: [](https://www.curseforge.com/minecraft/modpacks/putins-palace) 
Maybe the world generation mod: Terralith_v2.0.5 [](https://www.curseforge.com/minecraft/mc-mods/terralith)

**Comment by Flemmli97** [comment]
oh yeah i see now. caused by cloning it from 1.16 branch
