### ISSUE TITLE
Issue with Enderpearls

### ISSUE THREAD

**Issue by mahjerion** [Flemmli97/Flan#11]
#### Issue (The better the description the better i can solve the issue):
Player throws enderpearl and this happens. Server continues to crash when they log on (due to the pearl).

#### Steps to reproduce:
Don't have exact steps as it's a player on the server, but it seems like they throw the pearl and it happened.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.2
- Fabric: 10.5
- Flan: 1.0.8

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE): 
https://pastebin.com/s2YeQ8QL

**Comment by Flemmli97** [comment]
update the mod
