### ISSUE TITLE
OPENCONTAINER false not working

### ISSUE THREAD

**Issue by Hypn0iid** [Flemmli97/Flan#110]
#### Issue (The better the description the better i can solve the issue):
OPENCONTAINER false is not working on a group if the players added to that group try to open a chest with only their hands (without any blocks or items on their hands).

#### Steps to reproduce:
created a claim in the end (enderman xp farm on y level 1), created a group for my friends, open container = false but they can still open chests with only their hands.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.18.1
- Fabric(API): 0.12.12
- Flan: 1.16.5

**Comment by Flemmli97** [comment]
update
