### ISSUE TITLE
[Bug, Flan Forge, 1.18.1] ComputerCraft turtles completely bypass land protection

### ISSUE THREAD

**Issue by HonzaVinCZ** [Flemmli97/Flan#113]
#### Issue (The better the description the better i can solve the issue):
ComputerCraft turtles can completely bypass Flan land protection. 

![2022-01-03_17 44 34](https://user-images.githubusercontent.com/29098779/147957574-22e2f860-371a-44de-b04d-220fb2fb7309.png)

![2022-01-03_17 45 22](https://user-images.githubusercontent.com/29098779/147957582-e41bb143-581f-45f7-ab50-1c20cb4f24a7.png)

#### Steps to reproduce:
cc-tweaked-1.18.1-1.100.1
flan-1.18-1.6.6-forge
I created claim, placed turtle outside and launched turtle program "tunnel". Turtle destroys blocks inside my claim. 

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.18.1
- Forge: 39.0.9
- Flan: 1.6.6-forge

#### Other Mods (If you think it might be cause of an incompability. Adding a link + the used version will help greatly):
[ComputerCraft Tweaked](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked/files/3587947)

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE):
[latest.log](https://github.com/Flemmli97/Flan/files/7803047/latest.log)

**Comment by Flemmli97** [comment]
was it your claim and your turtle?

**Comment by HonzaVinCZ** [comment]
Yes but turtle isn't ownable afaik. So it shouldn't be owner related. Will try it in LAN with different account.

**Comment by Flemmli97** [comment]
it is. or rather the fake player behind the turtle doing the stuff has the same uuid as the player who placed the turtle

**Comment by HonzaVinCZ** [comment]
So I tested it on server and you're right. I logged in with two different accounts and I could only use turtle in my own claim but not in someone else claim. Sorry about that.
