### ISSUE TITLE
Player getting Stuck in Minecart when entering Property with No Entry Permissions. 

### ISSUE THREAD

**Issue by StoneLegion** [Flemmli97/Flan#114]
#### Issue (The better the description the better i can solve the issue):
Person was teleporting back and forth outside my property / inside my property when entering via Minecart on my Rail System in a Loop.

#### Steps to reproduce:
Prevent people from entering your land and build a really fast and long rail network into your property that has no exit.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.18.1
- Fabric(API): 0.45
- Flan: flan-1.18-1.6.6-fabric

#### Other Mods (If you think it might be cause of an incompatibility. Adding a link + the used version will help greatly):
I don't think this causes it but it does increase the speed so maybe bypasses a check at first if such a thing exists? 
audaki-cart-engine-mc1.18-fabric-v1.0.1.jar

**Comment by HonzaVinCZ** [comment]
That was always a problem with any land claiming mod. Don't build direct railway into your claim if you use entry deny.
Flan has one command that can help trapped player:
![Výstřižek](https://user-images.githubusercontent.com/29098779/148080600-2a36b19f-5f78-4b10-90d8-2bfd42154b46.PNG)
