### ISSUE TITLE
Server Crashes (or does nothing with more mods enabled) when trying to sell/buy claim blocks with Gunpowder

### ISSUE THREAD

**Issue by pahanakun** [Flemmli97/Flan#116]
When I first tried to buy/sell claimblocks with my full mod list, nothing happens. Claimblocks don't increase, and /balance from gunpowder-currency is unchanged.

The issue occurs with multiple buy/sell prices for claim blocks (1, 20, 25 etc)

full modlist: https://pastebin.com/1dVMwd8r

When disabling all mods except for gunpowder (and currency module), flan, fabric-api and kotlin, the problem gets worse: the server just crashes.

- Minecraft: 1.18.1
- Fabric(API): 0.45.0+1.18
- Fabric loader: 0.12.12
- Flan: 1.18-1.6.6 (also fyi your version format is the reverse of the conventional format other mods use, which list the minecraft version last. just a bit confusing)
- gunpowder-base-1.1.1.1+1.18.1
- gunpowder-currency-1.0.8+gunpowder.1.1.1.1.mc.1.18.1

error in server console: https://pastebin.com/CuDp47d5
crash report: https://pastebin.com/UHrLChcF

Also posting this issue on the gunpowder-currency page

**Comment by Flemmli97** [comment]
0bc81087fe51d27137d9b05f33e09098a21eaa46

**Comment by pahanakun** [comment]
I'm having troubles building the JAR with gradle, is there any way you could publish this as a release, or upload and link a working jar somewhere?

Gradle says the build is successful, but the JAR file is only 1kb and does nothing.
