### ISSUE TITLE
maxClaims is 500, but goes over 500 if you buy claims.

### ISSUE THREAD

**Issue by Namihyeon** [Flemmli97/Flan#121]
This is the current configuration.
You are using the Money and Sign Shops mod together.

{
  "__comment": "For help with the config refer to https://github.com/Flemmli97/Flan/wiki/Config",
  "configVersion": 4,
  "startingBlocks": 100,
  "maxClaimBlocks": 0,
  "ticksForNextBlock": 600,
  "minClaimsize": 1,
  "defaultClaimDepth": 10,
  "maxClaims": 500,
.
.
.
“buyclaims”:100,
“sellclaims”:50,

maxClaims is 500, but goes over 500 if you buy claims.

**Comment by Flemmli97** [comment]
yes this is intended. you buy additional claim blocks

**Comment by Namihyeon** [comment]
Can't set the maximum to buy blocks?
