### ISSUE TITLE
[Feature Request] Claim height limit

### ISSUE THREAD

**Issue by rabrunos** [Flemmli97/Flan#123]
#### Claim height limit
It would be nice if we could set the height limit for a claim.

Right now, if you claim land on the surface and some player wants to mine even if it's deep down, they won't be able to if it's in the claim rules.

That would make him have to go back and mine somewhere else or he would have to try to go around it as he wouldn't know the claim boundary but if the claim area is big it would be worse to go around it than to go back and try somewhere else .

Already with the possibility to set the claim height limit, all this problem would be solved and anyone could mine underneath without any problem.

**Comment by Flemmli97** [comment]
already a thing. claims only extend 10 blocks (default) below the claiming position
