### ISSUE TITLE
Crash when running 1.6.8 on 1.18.1 server

### ISSUE THREAD

**Issue by Alkiasan** [Flemmli97/Flan#125]
#### Issue (The better the description the better i can solve the issue):
On startup, server throws an error and crashes

#### Steps to reproduce:
Start Server

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.18.1
- Fabric(API): 0.45.2
- Flan: 1.6.8

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE):
https://pastebin.com/u7b8JnHR

**Comment by Flemmli97** [comment]
what other mods do you have?

**Comment by Alkiasan** [comment]
- additionaladditions 3.0.1
	- adorn 3.1.0+1.18.1
	- adventure-platform-fabric 5.0.0-SNAPSHOT via blockbot-discord
	- amplified_nether 1.0.1
	- apoli 2.2.2 via origins
	- arcanus 1.25
	- architectury 3.2.60
	- aurorasdeco 1.0.0+1.18
	- autoconfig1u 3.3.1 via image2map
	- backslot 1.2.3
	- bclib 1.2.4
	- betterdungeons 1.18-0.1.0
	- betterend 1.0.0
	- bettermineshafts 1.18-0.2.0
	- betterstrongholds 1.18-0.1.2
	- blacksmiths 1.1.0
	- blockbot-api 1.0.0 via blockbot-discord
	- blockbot-discord 2.0.0-beta
	- blockus 2.3.4+1.18.1
	- blue_endless_jankson 1.2.1 via jankson
	- calio 1.4.2 via apoli
	- cardinal-components-base 4.0.0 via trinkets
	- cardinal-components-entity 4.0.0 via trinkets
	- carpet 1.4.56
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48
	- cloth-config-lite 2.0.6 via omega-config-gui
	- clumps 8.0.4
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.13.0 via essential_commands
	- com_typesafe_config 1.4.1 via confabricate
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- confabricate 2.2.0-SNAPSHOT+4.1.1 via croptopia
	- config2brigadier 1.0.2 via taterzens
	- cosmetic-armor 1.2.0
	- croptopia 1.7.4
	- drinkbeer 3.0.2
	- ec-core 1.0.1-mc1.18.1 via essential_commands
	- emotecraft 2.1-SNAPSHOT-build.10
	- essential_commands 0.19.0-mc1.18.1
	- extraorigins 1.18-1
	- fabric 0.45.2+1.18
	- fabric-api-base 0.4.1+b4f4f6cd65 via fabric
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via taterzens
	- fabric-registry-sync-v0 0.9.0+befed49e65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- fabrictailor 1.8.0
	- ferritecore 4.0.0
	- fiber 0.23.0-2 via patchouli
	- flan 1.18.1-1.6.7
	- geckolib3 3.0.23
	- guild 0.3.8
	- harvest 1.2.12
	- hologram-api 0.2.1+1.18-pre5 via universal-graves
	- horizonrpmod 2.0.0
	- ibeeditor 2.0.10
	- icarus 1.9
	- image2map 0.2.2
	- invview 1.4.8-1.18+
	- io_leangen_geantyref_geantyref 1.3.11 via confabricate
	- jankson 4.0.0+j1.2.0 via adorn
	- java 17
	- kanos_config 0.1.4+1.14.4-1.17.1 via pehkui
	- krypton 0.1.6
	- ledger 1.2.0
	- libcd 3.0.3+1.16.3 via blockus
	- libgui 5.1.0+1.18 via additionaladditions
	- libninepatch 1.1.0 via libgui
	- lithium 0.7.7
	- medievalweapons 1.1.7
	- minecraft 1.18.1
	- minegate-moreblocks 1.1.8
	- modid 1.4.0
	- more_codecs 0.2.2+1.18 via player_roles
	- net_kyori_adventure-api 4.9.3 via adventure-platform-fabric
	- net_kyori_adventure-key 4.9.3 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.0.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-gson 4.9.3 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-plain 4.9.3 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- omega-config 1.1.0 via reroll
	- omega-config-gui 1.2.1-1.18.1 via reroll
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_spongepowered_configurate-core 4.1.1 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.1 via confabricate
	- org_spongepowered_configurate-gson 4.1.1 via confabricate
	- org_spongepowered_configurate-hocon 4.1.1 via confabricate
	- origins 1.3.1
	- origins-classes 1.2.4
	- packet_tweaker 0.2.0+1.18-pre1 via server_translations_api
	- patchouli 1.18.1-64-FABRIC
	- pehkui 3.1.0+1.14.4-1.18.1
	- placeholder-api 1.1.3+1.17.1 via essential_commands
	- player_roles 1.5.1
	- player_roles_api 1.5.1 via player_roles
	- playerabilitylib 1.5.0
	- polymer 0.2.0-beta.15+1.18.1 via universal-graves
	- polymer-legacy 0.1.9+0.2.0-beta.15+1.18.1 via polymer
	- quilt_base 1.0.0+1.18-SNAPSHOT via aurorasdeco
	- quilt_block_extensions 1.0.0+1.18-SNAPSHOT via aurorasdeco
	- reach-entity-attributes 2.1.1 via medievalweapons
	- reroll 1.4.0-1.18.1
	- roughlyenoughitems 7.1.356
	- seedfix 1.0.0 via amplified_nether
	- server_translations_api 1.4.8+1.18-pre1 via ledger
	- sgui 1.0.0-rc6+1.18-pre5 via invview
	- spark 1.7.2
	- starlight 1.0.1+fabric.0583973
	- styledchat 1.2.3+1.18
	- taterzens 1.8.0
	- terraform-wood-api-v1 2.0.2 via blockus
	- timeoutout 1.0.0+1.18
	- tradernpcs 1.0.3
	- trapexpansion 1.3.3
	- trinkets 3.1.0
	- universal-graves 2.0.0-beta.3+1.18
	- waystones 2.4.1
	- wires 1.0.5
	- worldedit 7.2.8+6008-1246d61
	- wthit 4.4.1
	- xaerominimap 21.22.6
	- xaeroworldmap 1.18.9
	- yungsapi 1.18-Fabric-35

**Comment by Flemmli97** [comment]
can you check if it crashes with only flan? and if not check which mod is causing it together with it?

**Comment by Alkiasan** [comment]
I would be unable to check it in a similar environment, since the server world uses blocks from other mods, and I have active players, sorry..

**Comment by Alkiasan** [comment]
All I can say is downgrading to the previous Flan version seems to fix the issue, so it seems to be specifically something changed in 1.6.8 causing it

**Comment by Flemmli97** [comment]
strange. so 1.6.7 already works?

**Comment by Flemmli97** [comment]
the 1.6.8 version one you had was probably for 1.16 or 1.17.

**Comment by Alkiasan** [comment]
Oh my god, it was. I'm an idiot, sorry for this hahahah
