### ISSUE TITLE
[Enchantment] New "Administrator" permission

### ISSUE THREAD

**Issue by Bo0sted** [Flemmli97/Flan#126]
A permission that grants someone all permissions and bypasses any restrictions set on a claim. This permission could only be granted by other administrators of the claim, or the owner themselves. 

This permission is similar to how Flan's "admin mode" works, but its implementing this functionality into a permission for claim's to have.

**Comment by Flemmli97** [comment]
redundant. you can just simply make a group that gives all permissions. and making that as a personal group you only need to do it once too
