### ISSUE TITLE
[Enchantment] GUI editor for Permission groups

### ISSUE THREAD

**Issue by Bo0sted** [Flemmli97/Flan#127]
Currently the only way to edit the permissions of permission groups is through commands. A GUI editor would be more convenient.

**Comment by Flemmli97** [comment]
already a thing. you can do everything via gui or command already

**Comment by Bo0sted** [comment]
> already a thing. you can do everything via gui or command already

I only see the option to edit global permissions through the GUI

**Comment by Flemmli97** [comment]
right click the group
