### ISSUE TITLE
[Enchantment] Prevents mobs / hostile mobs from entering claim and prevent creeper explosions

### ISSUE THREAD

**Issue by Bo0sted** [Flemmli97/Flan#128]
Expand the `CANSTAY` permission by including an option to restrict non-hostile and hostile mobs from entering your claim.

Side note: Add an option to toggle whether or not named entities should be disregarded by these checks, and an option to whitelist specific mobs

Also add a permission that restricts any blocks inside your claim being destroyed by a creeper

**Comment by Flemmli97** [comment]
reason why its prob not gonna be a thing:
1. too laggy since every mob would then need to check if they are in a claim and allowed to stay
2. disabling mob spawning and having a fence/wall does the same thing

also creeper explosion are toggled via explosion perm
