### ISSUE TITLE
[bug 1.16.5] flanforge 

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#129]
#### Issue (The better the description the better i can solve the issue):

with the help of a piston, I can move blocks on someone else's private, and with the help of a sticky one, I can move them to myself, please correct.

- Minecraft: 1.16.5
- Forge: If forge
- Flan: latest

**Comment by Flemmli97** [comment]
use the issue template properly

**Comment by MrJorman** [comment]
Can you please write to them?
