### ISSUE TITLE
[Issue] Language options

### ISSUE THREAD

**Issue by rabrunos** [Flemmli97/Flan#132]
#### Language options doesnt work

Setting to change language doesn't work, when I add my language ( pt_br ) it just doesn't open the server or the client.

Log file
https://paste.ee/p/Ip0JP

**Comment by Flemmli97** [comment]
while the error shouldnt be there is also no other language beside english atm

**Comment by rabrunos** [comment]
I translated the en_us file to pt_br!
And when creating the translated file with the name of pt_br, the mod does not recognize it.
I know the mod doesn't have the language natively, so I translated it and added mine!
