### ISSUE TITLE
Target selector in JSON text format not working

### ISSUE THREAD

**Issue by kristopher-pellizzi** [Flemmli97/Flan#133]
Hi! I am not sure if this is actually a bug or a design decision, as I was not able to find anything related to this topic in the wiki, so I did not use the template you provided for bug reports.

I am trying to set a claim message using owner's name as part of the message, e.g. "Welcome in [userName]'s claim".
I am using command "/flan claimMessage enter title text [JSON text component]".
I followed instructions from [this](https://minecraft.fandom.com/wiki/Raw_JSON_text_format#Entity_Names) page to build the JSON text component, and I ended up building the following:
{"text":"Welcome in ", "extra":[{"selector":"@s"}, " claim"]}.

This JSON component in the claimMessage command will set as a message "Welcome in @s claim", while it works as expected with command /tellraw, thus printing "Welcome in [userName] claim".

Is this a problem that is going to be solved or it is intended?

**Comment by Flemmli97** [comment]
ye you cant use targets in that since there is no target. intended.
