### ISSUE TITLE
[1.16.5] bug Flan - Using the Quark mod (right-click to collect harvesting)

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#135]
#### Issue (The better the description the better i can solve the issue):

Players in a foreign region can harvest using the right mouse button, set up the Harvest of quarks. And they can also open double doors, also Tweak Quark, Double door opening.

#### Steps to reproduce:

Install Quark mod, go to the player on the region, open the double doors (already a bug), then poke at the harvest of the PCM and collect it thereby (bug)

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.5
- Forge: 1.16.5 - 36.2.26
- Flan: flan-1.16.5-1.7.0-forge.jar

#### Other Mods (If you think it might be cause of an incompability. Adding a link + the used version will help greatly):

Quark. https://www.curseforge.com/minecraft/mc-mods/quark

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE):

No logs.

**Comment by Flemmli97** [comment]
they need to check RightClickBlock#getUseBlock on their side. report it to them
