### ISSUE TITLE
[Feature Request] Permission to add self-owned subclaims

### ISSUE THREAD

**Issue by orlouge** [Flemmli97/Flan#136]
The use case would be a claim (perhaps an admin one) representing a town in which each resident adds subclaims for their own builds. Each resident would be able to modify streets and other public builds, but private builds would have their own permissions. If having to introduce subclaims with different owners is too big a change, an alternative could be keeping the owner of the outer claim as the owner of the subclaim but automatically adding the creator of the subclaim to a certain permission group, which would still require a new add claim permission.

**Comment by KatNyxion** [comment]
could this not be done with claim and subclaims as it is? just the claim owner setting the sublaim "owner" as co owner? or are you wanting people to be allowed to subclaim in other peoples claims? that feels like it would need another type of permission to work properly

**Comment by Flemmli97** [comment]
yes this is already possible by adding the player to e.g. co-owner in a subclaim
