### ISSUE TITLE
[Feature Request] pls add new commands.

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#138]
Please add easy commands to add players to private and delete them. For example: /rg addmember {player}, /rg addowner {player} - this adds players. /rg removeowner {player}, /rg removemember {player} - this removes players, please

**Comment by MrJorman** [comment]
And give me your discord, i I want to order private events from you for things from mods so that they don't break the private.

**Comment by Flemmli97** [comment]
already a thing. and discord is on modpage
