### ISSUE TITLE
The permissions do not seem to work

### ISSUE THREAD

**Issue by IDMCtech** [Flemmli97/Flan#139]
### Modloader

Fabric

### Minecraft version

1.18.1

### Modloader version

0.13.3 of fabric

### Mod version

1.7.2

### Description

https://cdn.discordapp.com/attachments/935989994735169546/946216564015919204/2022-02-23_19-25-23.mp4 the permissions do not apply

### Steps to reproduce

1. Try to add permissions to a group
2. add that player to said group
3. Watch him try to use said permissions

### Mods that might affect the issue

https://cdn.discordapp.com/attachments/861270140339748876/946224044477386793/unknown.png

### Logs

N/A no logs for broken blocks

**Comment by Flemmli97** [comment]
it works for me. what does it say for the other player?

**Comment by Flemmli97** [comment]
closing stale issue. if still present reopen/create a new issue
