### ISSUE TITLE
Blocks not protected- AE2 and Industrial Revolution machines

### ISSUE THREAD

**Issue by ProsperCraft** [Flemmli97/Flan#14]
#### Issue (The better the description the better i can solve the issue):
The AE2 system is not protected from players opening the terminal and taking things(yes can be done with a security terminal).

The Industrial Revolution machines were not protected as well.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.3
- Fabric: fabric-api-0.25.0+build.415-1.16.jar
- Flan:flan-1.16.2-1.1.4.jar

#### Other Mods (If you think it might be cause of an incompability):

[The Adventures of Halk for 1.16](https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk)

**Comment by Flemmli97** [comment]
ae2 wont be supported. they arent either inventorys or have special implementation of inventory that would require a dependency on ae2 to check for it. ir machines will be included in the next update

**Comment by Flemmli97** [comment]
actually i added ae2 by including all tile entitys now.
