### ISSUE TITLE
Issue with custom NPCs

### ISSUE THREAD

**Issue by mmasdivins** [Flemmli97/Flan#141]
### Modloader

Forge

### Minecraft version

1.16.5

### Modloader version

36.2.22

### Mod version

1.7.2

### Description

When setting a claim the other players cannot interact with an npc from custom NPCs, even with the permission to interact with fake players

### Steps to reproduce

1. Install the custom NPCs with Flan
2. Set a simple custom  NPC
3. Claim the region where the NPC is
4. Try to interact with the NPC

### Logs

No logs

**Comment by Flemmli97** [comment]
cause they are not fake players. its either villager or animal interaction

**Comment by mmasdivins** [comment]
Yes, sorry my bad I was too quick to write an issue, thanks for your response!
