### ISSUE TITLE
Hosti

### ISSUE THREAD

**Issue by AICodeMaster69** [Flemmli97/Flan#144]
### Modloader

Fabric

### Minecraft version

1.18.2

### Modloader version

most recent

### Mod version

Flan 1.7.5

### Description

Hello, we want to disable mob spawning for our land claim, but it says "non-editable" in /Flan Menu

### Steps to reproduce

1. Step one

### Logs

![image](https://user-images.githubusercontent.com/102373292/160148182-9a4ef4c8-5bde-40a3-9cd2-5e8250f10865.png)

**Comment by Flemmli97** [comment]
join the discord for help
