### ISSUE TITLE
unlockDropsCmd text shows up when deathbox is disabled

### ISSUE THREAD

**Issue by WilcoM** [Flemmli97/Flan#146]
### Modloader

Fabric

### Minecraft version

1.18.2

### Modloader version

1.18.2-0.13.3

### Mod version

1.18.2-1.7.5

### Description

The `Your deathitems are protected. Use %1$s to unlock them for other players` text shows up on death, even when deathboxes are disabled.

Clearing this text in the lang file will still send an empty line in chat.

### Steps to reproduce

1. Install mod
2. die in survival mode
3. deathbox message shows up
4. edit lang file and empty the unlockDropsCmd text
5. restart server
6. die in survival mode; empty line will be sent in chat

### Logs

Not an issue identified in logs.

**Comment by Flemmli97** [comment]
you want to disable protecting drops or just the message? cause if you disable item protection you will also disable the message

**Comment by PsyBooty** [comment]
How do i disable item protection on deth?
Is this: "LOCKITEMS": "ALLTRUE",?
Btw just a sugestion, this should be disabled by default imo.

**Comment by ktunkiewicz** [comment]
This message also shows up when `doKeepInventory` is enabled in game rules, which makes totally no sense, because there will be no items on the ground. IMO there should be a check for this in the code, and nothing should be displayed if doKeepInventory is enabled
