### ISSUE TITLE
[Feature Request]: Update 18.1 to 1.7

### ISSUE THREAD

**Issue by juanggcc** [Flemmli97/Flan#150]
### Suggestions

1.18.1 version is being used more at the moment. It would be awesome if we get the same features there too, until all other mods are in 18.2 and we can transition.

If it is not too hard to do

Thanks for the work! :)

**Comment by Flemmli97** [comment]
sorry but this isnt happening. since that would mean i need to maintain another version which is too much

**Comment by juanggcc** [comment]
you would have to mantain it just one or two versions, until 1.18.2 gets standarized :(

**Comment by juanibal** [comment]
for example, you added economy integration with a mod that is still in the 18.1 (as most mods) XD
