### ISSUE TITLE
Buying blocks with "ITEM" and vanilla item wont work and deletes and changes config

### ISSUE THREAD

**Issue by YaBoi2Fish** [Flemmli97/Flan#153]
### Modloader

Fabric

### Minecraft version

1.18.1

### Modloader version

0.13.3

### Mod version

flan-1.18.1-1.7.3-fabric.jar

### Description

When i'm using buy/sell type with "ITEM" and add to ingredient something from vanilla it wont work. After i enter the world the ingredient value goes back to default e.g. ingredient": ["diamond"] to ingredient": [ ]. I've tried without apostrophe, with the value put to the next column and it wont work.

### Steps to reproduce

1. Step one just run the game.

### Logs

https://gist.github.com/2Fish-Is-Here/0cb75f8e6d69f742700e83a5e522b210

**Comment by Flemmli97** [comment]
not how you use it. check any vanilla recipe json/mc wiki for the correct syntax
