### ISSUE TITLE
[Bug] Mobspawn doesnt work

### ISSUE THREAD

**Issue by xR4YM0ND** [Flemmli97/Flan#154]
### Modloader

Fabric

### Minecraft version

1.18.2

### Modloader version

0.13.3

### Mod version

1.7.6

### Description

is set MOBSPAWN to ALLTRUE ( to disable tem , i tryed wit ALLFALSE as well ) but monsterns are spawn in the overworld

### Steps to reproduce

globalworldpermission
minecraft:overworld
MOBSPAWN to ALLTRUE 

hop in the overworld and test it

### Logs

https://gist.github.com/SpigotDE/7be8085e92e12f758e4dd0dfb3d395dd

**Comment by xR4YM0ND** [comment]
Maybe make a permission like DIFFICULTY or so

**Comment by Flemmli97** [comment]
cannot reproduce. make sure its not in an admin claim that has it set to false

**Comment by xR4YM0ND** [comment]
A skeleton from TinySkeleton mod spawned in the overworld

No claims are present

**Comment by xR4YM0ND** [comment]
Ok now it works, i tested it today and no mobs spawn normally , but spawner mobs do spawn ( tested with spider spawner )

**Comment by xR4YM0ND** [comment]
But i think its good , so you can still make mobfarms

**Comment by Flemmli97** [comment]
closing it then if its resolved
