### ISSUE TITLE
"This is <UNKNOWN>'s claim" message when using inspection tool

### ISSUE THREAD

**Issue by Sebas-Re** [Flemmli97/Flan#155]
### Modloader

Fabric

### Minecraft version

1.18.1

### Modloader version

0.13.3

### Mod version

1.7.3

### Description

Some claims shows "This is UNKNOWN's claim" message when using inspection tool or the command (/flan ClaimInfo). Does that mean the user haven't logged back on for +30 days, but the mod failed to remove the claim?
![flan 2](https://user-images.githubusercontent.com/32151264/165415613-4a0839c8-9af4-4536-82fb-13c9ae30aae8.png)
![flan 1](https://user-images.githubusercontent.com/32151264/165415618-2072344b-9b93-40c6-8cd8-ee7f258c425a.png)

### Steps to reproduce

Idk how to reproduce this, as it happens with some claims, not all of them.

The only thing I can think of is that this claim has a Co-Owner and another custom group added.

### Logs

https://gist.github.com/Sebas-Re/d96bc1599f1a7a4a756b8d71ee73f62c

**Comment by Flemmli97** [comment]
this only happens if it fails to find a player with the claim owners uuid which should only happen if you set it to someone who doesnt exit

**Comment by Flemmli97** [comment]
closing stale issue. if still present reopen/create a new issue
