### ISSUE TITLE
The Waystones addition broke waystones

### ISSUE THREAD

**Issue by Zunwolf1896** [Flemmli97/Flan#157]
### Modloader

Fabric

### Minecraft version

1.18.2

### Modloader version

0.13.3

### Mod version

1.7.6

### Description

Waystones was added to become unbreakable inside flan claims, a nice feature, but Waystones has its own feature so that only the owner of the waystone can break it. 
Before the Waystone addition to the Flan mod, you needed to have "interact block" and "open container" enabled to be able to open the waystone GUI and use it. Now even with the two options enabled, people who do not own the flan area are unable to interact with the waystones at all, despite the permisions being enabled. 

### Steps to reproduce

1. Install version 1.7.6 flan on the server, along with version 2.5.0 Fabric Waystones on the serverr. 
2. Create a claimed area using normal Flan options.
3. Place a waystone inside your area,
4. enable interact with containers and open containers 
5. be unable to use the waystone if you do not own the flan area.

### Mods that might affect the issue

https://www.curseforge.com/minecraft/mc-mods/fabric-waystones

### Logs

There are no logs, there's no error that comes up

**Comment by Flemmli97** [comment]
i can interact with it fine. the waystone thing was just a change in the default config so if you updated from an older version this change will not be reflected. you need to change it manually in the config. like add "waystones" to "interactBlockBlacklist"
