### ISSUE TITLE
Mob explosions can break Create Glue in a reigion that disallows explosives

### ISSUE THREAD

**Issue by notdonte** [Flemmli97/Flan#159]
### Modloader

Fabric

### Minecraft version

1.18.2

### Modloader version

0.51.1

### Mod version

1.7.8

### Description

Mob explosions such as creepers exploding inside claims can break create super glue inside structures, rendering them inoperable.

### Steps to reproduce

1. Install an instance with both Flan and Create Fabric
2. Claim area and designate explosions as off.
3. Build a create contraption that uses Super Glue
4. Spawn a creeper or other exploding mob, and make it explode.
5. Explosion affects no blocks, but removes super glue.

### Mods that might affect the issue

https://www.curseforge.com/minecraft/mc-mods/create-fabric/files/3798590
[Create 1.18.2 v0.4.1 Patch 1]

### Logs

n/a

**Comment by notdonte** [comment]
Turning off mob greifing fixes the issue but not when something like TNT is launched into the claim, or when a player is given an exploding status effect through other mods.

**Comment by Flemmli97** [comment]
glue mechanics changed now. it can only be removed by the player so closing this
