### ISSUE TITLE
[Feature request] SubClaim customization

### ISSUE THREAD

**Issue by CodedSakura** [Flemmli97/Flan#16]
It would be really handy to be able to:
- give SubClaims names,
- add specific SubClaims to groups (so they inherit the permissions),
- option to restrict group permissions to a specific SubClaim.

I believe that these enhancements would greatly increase the use-cases of this mod!

P.S.: It would be nice to always show the claim while holding the `claimingItem`.

**Comment by Flemmli97** [comment]
you can already also create groups for subclaims. though idk if thats exactly what you want

**Comment by CodedSakura** [comment]
Oh, didn't know. Is it for specific subclaims separately or for all of them together?
Also, how do you even accomplish that? I can't seem to find anything on the wiki that says how to do that..

**Comment by Flemmli97** [comment]
you use /flan switchMode to switch into subclaim mode. and everything you do will apply to subclaims if possible. so open the menu in a subclaim to add/edit group and permissions for that subclaim
