### ISSUE TITLE
[Bug] [1.18.2] Cannot interact with Crafting Tables or Waystones

### ISSUE THREAD

**Issue by MoXAriApph** [Flemmli97/Flan#161]
### Modloader

Forge

### Minecraft version

1.18.2

### Modloader version

40.0.44

### Mod version

1.18.2-1.7.6

### Description

Some perms are not functioning properly

Currently we cannot open Shulker Boxes, use Crafting tables or Waystones when a claim is made

### Steps to reproduce

1. Create a claim
2. Set OpenContainer and InteractBlock to true
3. Have a non-owner of the claim try to use a waystone or crafting table

Have tested 

Admin Claim
Non-Admin Claim
Permission Groups
Global Perms
Transferring to other people

`waystones` is in the InteractBlockBlacklist, does not change whether adding or removing it

### Mods that might affect the issue

3dskinlayers-forge-1.4.3-mc1.18.2.jar
Amplified_Nether_v1.1.1.jar
balm-3.0.2+0.jar
BetterPingDisplay-1.18.2-1.1.jar
BetterThirdPerson-Forge-1.18.2-1.7.3.jar
carryon-1.18.2-1.17.0.8.jar
catalogue-1.6.1-1.18.2.jar
chat_heads-0.6.0-fabric-1.18.1.jar
Chunky-1.2.164.jar
collective-1.18.2-4.25.jar
ColtCosmeticArmorMod-1.4.2.jar
configured-1.5.3-1.18.2.jar
CosmeticArmorReworked-1.18.2-v2.jar
curios-forge-1.18.2-5.0.7.0.jar
entityculling-forge-mc1.18-1.5.1.jar
EquipmentCompare-1.18.1-1.2.12.jar
FallingTree-1.18.2-3.4.2.jar
fancymenu_forge_2.6.4_MC_1.18.2.jar
farsight-1.18.2-1.8.jar
ferritecore-4.2.0-forge.jar
flan-1.18.2-1.7.6-forge.jar
Iceberg-1.18.2-1.0.40.jar
InventoryHud_[1.18].forge-3.4.4.jar
itlt-1.18-2.1.0.jar
jei-1.18.2-9.5.5.174.jar
konkrete_forge_1.3.3_MC_1.18-1.18.1.jar
moredragoneggs-3.1.jar
MouseTweaks-forge-mc1.18-2.21.jar
OptiFine_1.18.2_HD_U_H7.jar
radium-0.7.10.jar
SereneSeasons-1.18.2-7.0.0.14.jar
starterkit_1.18.2-3.2.jar
Terralith_v2.2.1a.jar
trashslot-forge-1.18.1-11.0.2.jar
WaterStrainer-1.18.2-13.0.0.jar
waystones-forge-1.18.2-10.0.0.jar
worldedit-mod-7.2.10.jar
wthit-forge-4.8.1.jar
XaerosWorldMap_1.20.6_Forge_1.18.2.jar
Xaeros_Minimap_22.5.0_Forge_1.18.2.jar

### Logs

Server log with us attempting to use a waystone at the very end, nothing is written to log
Same in debug.log

https://paste.gg/p/anonymous/a9793027f82942b18a8fcd28c99ad1b8

**Comment by Flemmli97** [comment]
cannot reproduce. try using only flan and waystones to test

**Comment by Flemmli97** [comment]
closing stale issue. if still present reopen/create a new issue
