### ISSUE TITLE
Flan claims and Minecolonies colony claims overlap

### ISSUE THREAD

**Issue by Pandaw15** [Flemmli97/Flan#162]
### Modloader

Forge

### Minecraft version

1.18.2

### Modloader version

40.1.0

### Mod version

1.7.5

### Description

Flan claims and Minecolonies colony claims overlap.

If you claim with flan, someone else can create a colony that will overlap on yours
If you make a colony, someone else can go in your colony and claim over yours

In both cases, no one is allowed to interact with the overlapping area, as both claims work at the same time (accessing your townhall seems to work tho).

### Steps to reproduce

1. Claim an area with flan
2. With another account, go near the claim and create a colony

1. Create a colony
2. With another account, go in the colony and claim an area

### Mods that might affect the issue

https://www.curseforge.com/minecraft/mc-mods/minecolonies

Version 1.0.806-ALPHA

### Logs

I can't access my server since it expired but it really isnt hard to reproduce and see the logs created then, Im sorry.
However I think it may really be a critical bug for servers.

**Comment by Flemmli97** [comment]
cant do anything about that. even if i check for overlap on my side minecolonies doesnt so by placing buildings and it auto expanding a colony claim it just cuts into flan anyway

**Comment by Pandaw15** [comment]
Maybe we can try to contact the dev for Minecolonies, and if they're aware of the issue each one of you can check for the other's claim before trying to claim. Ill report the issue to them.
