### ISSUE TITLE
Can't set ingredient for buying claimblocks

### ISSUE THREAD

**Issue by EnderGirl1500** [Flemmli97/Flan#165]
### Modloader

Fabric

### Minecraft version

1.18.2

### Modloader version

0.14.8

### Mod version

1.7.9

### Description

Please just tell me which is the ID for copper ingot. You didn't even put an example on the wiki! I've been looking for the recipes/ids/ingredients and I don't even know what to type. I've tried ["minecraft:copper_ingot"], "minecraft:copper_ingot", [minecraft:copper_ingot], ["item.minecraft.copper_ingot"], "item.minecraft.copper_ingot", [item.minecraft.copper_ingot] and nothing works!

### Steps to reproduce

1. N/A

### Logs

I don't think this is needed

**Comment by Flemmli97** [comment]
it uses crafting recipe output formatting
like `"ingredient": {
      "item": "minecraft:apple"
    }`

and this is not a support section
