### ISSUE TITLE
Log spam with "enableLogs": false

### ISSUE THREAD

**Issue by LucilleTea** [Flemmli97/Flan#17]
#### Issue (The better the description the better i can solve the issue):
Every 5 minutes these messages will be output to the server log, even when the server is empty:
```
25.11 07:08:30 [Server] Server thread/INFO Saving claims for world ResourceKey[minecraft:dimension / minecraft:overworld]
25.11 07:08:30 [Server] Server thread/INFO Saving claims for world ResourceKey[minecraft:dimension / minecraft:the_nether]
25.11 07:08:30 [Server] Server thread/INFO Saving claims for world ResourceKey[minecraft:dimension / minecraft:the_end]
```
In my flan_config.json I have `"enableLogs": false`, the default.

#### Steps to reproduce:
Run Flan on a server with the default config file, leave the server open for a while.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.4
- Fabric: 0.10.6+build.214
- Flan: 1.1.5

#### Other Mods (If you think it might be cause of an incompability):
I don't think they should matter, they are in the log.

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE): 
[Full log](https://pastebin.com/VH2s8uQp) (I don't know why it thinks it's offensive, there's nothing bad there I promise)

**Comment by Flemmli97** [comment]
c6b5399488a8e126c1b434d7a69ebaf0e957eac6
