### ISSUE TITLE
[Feature Request]: Diamond Economy Integration

### ISSUE THREAD

**Issue by TheCherry** [Flemmli97/Flan#171]
### Suggestions

Will be nice if you can support: https://www.curseforge.com/minecraft/mc-mods/diamond-economy

**Comment by diznover** [comment]
I wrote this [Feature Request] for another mod, but I think I can write it here. 

In the [diamond economy](https://modrinth.com/mod/diamond-economy) modification, there is a game currency inside, inside the game digital wallet can be replenished with in-game items, and in your modification there is the possibility of private territory. What if the players had to pay for what they owned the territory for? With any period of time, a day, a week, a month, and they would pay a certain amount of money for 200 blocks of territory, for example, a player will privatize 800 blocks, and 200 blocks is worth 10 conventional units of currency, so he must pay 40 units of currency. I think it would be cool and the players wanted to get back into the game.

**Comment by Flemmli97** [comment]
towny like systems are not planned

**Comment by Flemmli97** [comment]
otherwise. closed in 26d245968395df119fa8ea2f48cc6a31d4bbb050
