### ISSUE TITLE
[Feature Request]: Potion Effect Night Vision duration should be longer than 10 seconds minimum.

### ISSUE THREAD

**Issue by NoThrottle** [Flemmli97/Flan#172]
### Suggestions

In normal vanilla Minecraft, the Night Vision effect starts flickering when it is about to run out, this happens when it has 10 seconds remaining. Since the default duration of potion effects are 10 seconds, and are replenished every 5, this means having a night vision potion effect will be eternally blinking. 

### Solution

1. When adding a potion effect, make it possible to specify a minimum and maximum duration. (Although minimum should be enough)
2. Have a setting in the config that sets the default minimum or maximum potion effect duration.

**Comment by Deses** [comment]
What does this has to do with FLAN?

**Comment by Flemmli97** [comment]
b9347c1e03a12e7365d1f00070dd40cefcf8a875 for now night vision gets 20 sec instead of 10. others stay at 10
