### ISSUE TITLE
[1.18.2, Forge] Claim interaction bug with Chisels & Bits

### ISSUE THREAD

**Issue by HonzaVinCZ** [Flemmli97/Flan#173]
### Modloader

Forge

### Minecraft version

1.18.2

### Modloader version

40.1.51

### Mod version

flan-1.18.2-1.7.10-forge

### Description

I have some weird bugs happening on my Forge server with Flan. When someone makes a new claim, other players are allowed to make certain interactions with given claim. I have a small list of interactions that should be restricted but are allowed through this bug. Note that config file is default, happens even on a new world. Also the same thing happens to adminClaim.
- Block place - Allowed
- Block break - Restricted (as supposed)
- Inventory interaction - Allowed
- Pressure plates - Restricted (as supposed)
- Door interaction - Allowed

My mate reported that when he does things that he shouldn't be allowed to do, it shows him a message "You can do that here" but game allows him to do his stuff anyway. No group or permission was given.

I did not have such problem before I added few mods that are just content related and do not influence block interaction in any way, in other words there is no other mod like Flan for land management. 
I'm not sure if I can filter off which mod could do that because there is plenty of them. Best I can do is provide mod list and/or try go mod by mod but it will take some time...

### Steps to reproduce

Unable to reproduce. Bug is present ingame since game launch.

### Mods that might affect the issue

X

### Logs

https://gist.github.com/HonzaVinCZ/24a50b54f1238406513edc8df367b3dd

**Comment by HonzaVinCZ** [comment]
Well I have found the cause of this issue. It seems like there is a major bug happening while running Flan and Chisels & Bits.

Without Chisels & Bits I can't reproduce this issue.

- Mod list and placed blocks inside my claim by other player:

![image](https://user-images.githubusercontent.com/29098779/180166945-fe3e3b06-1f51-4b9d-9fc6-6a11f3e7945b.png)

- Other player's view after placing blocks and checking claim:

![image](https://user-images.githubusercontent.com/29098779/180167741-eae0969b-a451-4a7d-9bd5-6dac9b060602.png)

**Comment by Flemmli97** [comment]
on chisel and bits:
https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/version/latest/platforms/forge/src/main/java/mod/chiselsandbits/forge/events/RightClickEventHandler.java#L16 

they should check if any other mods disable item/block interaction via RightClickBlock#getUseBlock/getUseItem

**Comment by marchermans** [comment]
@Flemmli97 What exactly are you talking about?

There is no class RightClickBlock, neither in Minecraft nor in C&B.
Neither can I find the methods you mentioned anywhere.
Can you please elaborate this point?

Sorry that I bring this up again, it was reported only now to me.

And you are not cancelling the event, so I have no way of knowing that the interaction is not allowed to proceed.

**Comment by Flemmli97** [comment]
RightClickBlock is a forge event. 

idk what exactly changed with 1.19 but here in 1.18:
[https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/version/1.18.2/platforms/forge/src/main/java/mod/chiselsandbits/forge/events/RightClickEventHandler.java](https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/version/1.18.2/platforms/forge/src/main/java/mod/chiselsandbits/forge/events/RightClickEventHandler.java)

the event handles item use on block and block use. cancelling the event causes neither to be processed yes. but you can also can only disable one of them without cancelling the whole event
