### ISSUE TITLE
Not able to interact with signs with "run command"

### ISSUE THREAD

**Issue by TheCherry** [Flemmli97/Flan#174]
### Modloader

Fabric

### Minecraft version

1.19

### Modloader version

latest - 0.14.6 ?

### Mod version

1.7.10

### Description

We use signs with a run_command nbt tag.
The claim is in admin mode and we are not able to let the users interact with that signs.

### Steps to reproduce

1. Get a sign and place it:
/give @s minecraft:jungle_sign{BlockEntityTag:{"GlowingText":1b, Text1:'{"text":"","clickEvent": {"action":"run_command","value":"tp 534 122 655"}} ',Text2:'{"text":"Zu den"}',Text3:'{"text":"Masken &"}', Text4:'{"text":"Helloween"}'},display:{Name:'{"text":"TP Masks"}'}} 10

2. Have a claim with admin flag
3. let a another player try to teleport

### Logs

-

**Comment by Flemmli97** [comment]
you can blacklist blocks via config being affected by claim protection
