### ISSUE TITLE
The claim ends at y level -6

### ISSUE THREAD

**Issue by Drew-Chase** [Flemmli97/Flan#175]
### Modloader

Fabric

### Minecraft version

1.19

### Modloader version

0.57.0

### Mod version

1.7.10

### Description

The claim ends at y level -6

### Steps to reproduce

1. Make a claim
2. Add entering and leaving text
3. Go to y level -6

### Logs

[latest.log](https://github.com/Flemmli97/Flan/files/9163339/latest.log)
https://paste.gg/p/anonymous/c4f686b989e043bcb10d5a82669cfbb1/files/5148b918554c4d6a8c95026c79da5c98/ra

**Comment by Flemmli97** [comment]
yes claims dont go all the way down by default. they auto extend if you build
