### ISSUE TITLE
[BUG 1.19 Fabric] ender pearls spawn endermite

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#176]
### Modloader

Fabric

### Minecraft version

Minecraft 1.19

### Modloader version

Fabric latest 1.19

### Mod version

flan-1.19-1.7.10-fabric

### Description

When I throw ender pearls, I can summon an endermite on someone else's private and he can kill the owner. I don't want to prohibit the use of ender pearls in private, but I want to make sure that endermit is not called in this way in private if someone else's player throws ender pearls.

### Steps to reproduce

When I throw ender pearls, I can summon an endermite on someone else's private and he can kill the owner. I don't want to prohibit the use of ender pearls in private, but I want to make sure that endermit is not called in this way in private if someone else's player throws ender pearls.

### Mods that might affect the issue

Flan

### Logs

no logs

**Comment by Flemmli97** [comment]
closed. 4a3faf9eef50a147cf3bbf6d7eeb0110f16b1b47
