### ISSUE TITLE
[BUG 1.19 Fabric] A striking blow with a sword touches animals, players in private, where PVP is turned off.

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#177]
### Modloader

Fabric

### Minecraft version

Minecraft 1.19

### Modloader version

Fabric latest 1.19

### Mod version

flan-1.19-1.7.10-fabric

### Description

A striking blow with a sword touches animals, players in private, where PVP is turned off.

### Steps to reproduce

A striking blow with a sword touches animals, players in private, where PVP is turned off.

### Mods that might affect the issue

Flan

### Logs

no logs

**Comment by Flemmli97** [comment]
cannot reproduce. if by striking blow you mean the sweeping yes it is blocked

**Comment by Flemmli97** [comment]
closing stale issue. if still present reopen/create a new issue
