### ISSUE TITLE
[BUG 1.19 Fabric] I can't disable the message function when logging in/out of private.

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#178]
### Modloader

Fabric

### Minecraft version

Minecraft 1.19

### Modloader version

Fabric latest 1.19

### Mod version

flan-1.19-1.7.10-fabric

### Description

I want to disable the feature in the mod so that it is impossible for players and administrators to leave messages from entering/exiting the player's region.

### Steps to reproduce

I want to disable the feature in the mod so that it is impossible for players and administrators to leave messages from entering/exiting the player's region.

### Mods that might affect the issue

Flan

### Logs

no logs

**Comment by Flemmli97** [comment]
its a permission already: CLAIMMESSAGE.
and admins can always bypass stuff
