### ISSUE TITLE
[Feature Request]: Make the private display visually, not through the effect, for example, WorldEditCUI, Create, and other private mods.

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#179]
### Suggestions

Make the private display visually, not through the effect, for example, WorldEditCUI, Create, and other private mods.

### Solution

Make the private display visually, not through the effect, for example, WorldEditCUI, Create, and other private mods.

**Comment by Flemmli97** [comment]
will not depend on other mods for this usecase. sry
