### ISSUE TITLE
[BUG 1.19 Fabric] Ender's crystal explodes players in their region.

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#181]
### Modloader

Fabric

### Minecraft version

Minecraft 1.19

### Modloader version

Fabric latest 1.19

### Mod version

flan-1.19-1.7.10-fabric

### Description

Players place Ender crystals next to the players' region, and blow them up as the damage reaches them.

### Steps to reproduce

Players place Ender crystals next to the players' region, and blow them up as the damage reaches them.

### Mods that might affect the issue

Flan + Vanilla Minecraft

### Logs

no logs

**Comment by Flemmli97** [comment]
nothing can do about that. end crystals dont know who blew them up
