### ISSUE TITLE
[Feature Request]: to do this, if the owner of the region does not enter the game for 7 days, then the private is automatically deleted.

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#183]
### Suggestions

to do this, if the owner of the region does not enter the game for 7 days, then the private is automatically deleted.

### Solution

to do this, if the owner of the region does not enter the game for 7 days, then the private is automatically deleted.

**Comment by MrJorman** [comment]
there are a lot of fake regions of players on the server who do not play, I would like your mod to delete regions if the player does not log into the game (on the server) for 7 days so that I can turn this function on and off and set the days.

**Comment by Flemmli97** [comment]
already a thing. inactivityTimeDays in config
