### ISSUE TITLE
Server crash with the mod

### ISSUE THREAD

**Issue by FumpleWumper** [Flemmli97/Flan#184]
### Modloader

Fabric

### Minecraft version

1.18.2

### Modloader version

0.14.9

### Mod version

1.8.1

### Description

The server crashes briefly after a player joins

### Steps to reproduce

1. Join a server with Flan
2. Wait only a few seconds
3. Server Crash

### Logs

https://gist.github.com/FumpleWumper/c6070127ee78241df1ac8cf2f60f376b

**Comment by itsdinkd** [comment]
This also happened to me... on single player.


https://gist.github.com/itsdinkd/eea94ccf5ceac8b57a2316f793a79686

**Comment by Flemmli97** [comment]
fixed in 4fc8713d3335f21c0fbbf3f500d8a698eb20eacb
