### ISSUE TITLE
Server Crash 1.19.2 Fabric

### ISSUE THREAD

**Issue by Spudstak** [Flemmli97/Flan#187]
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

Fabric - 0.14.9

### Mod version

flan-1.19-1.8.1-fabric

### Description

Loading up a world causes the server to crash.

### Steps to reproduce

1. Join a world.
2. Move around a bit.
3. Crash.

### Mods that might affect the issue

Looks like lucko perms crash. I noticed that another report for 1.18.2 had the issue fixed, I'm guessing the 1.19.2 version just needs the same change.

### Logs

https://paste.gg/p/anonymous/d65ac5b9091d421a9bc6bed0744fbb93

**Comment by Flemmli97** [comment]
bewitchment uses an old version of fabric permission api. they need to update it. or dont use that mod
