### ISSUE TITLE
World crash  1.19.2

### ISSUE THREAD

**Issue by 3dguru** [Flemmli97/Flan#188]
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

fabric  0.60.0

### Mod version

1.8.1

### Description

loads world but after 15 seconds the game crashes

### Steps to reproduce

1. loads world
2. walking around for 15 seconds then crash

### Logs

https://pastebin.com/5g2QZmFj

**Comment by Flemmli97** [comment]
spark needs to update fabric permission api
