### ISSUE TITLE
Flan causes invalid player data to be sent.

### ISSUE THREAD

**Issue by Kichura** [Flemmli97/Flan#189]
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

0.14.9

### Mod version

1.8.1

### Description

When using flan with specific players, Sometimes they will get "invalid player data" and are completely locked out forever until their entire player data is wiped from disk which causes tons of annoyances in process,

And this issue becomes even more noticable when datapacks are installed too.

### Steps to reproduce

1. Install flan onto the server,
2. Have tons of players on the server at once doing their own claims and whatnot,
3. Relog and expect "Invalid player data" to occur at some point.

### Mods that might affect the issue

(I could not find any that may cause issues - [But mod list is here](https://pastebin.com/raw/V7VzujfJ))

### Logs

[Server] [INFO] [server connection] Mesa3D -> smp has connected
[Server] [INFO] [connected player] Mesa3D (<ip address withheld>): kicked from server smp: multiplayer.disconnect.invalid_player_data
[Server] [INFO] [server connection] Mesa3D -> smp has disconnected

Otherwise there is nothing in the backend server's logs that tell anything.

**Comment by Flemmli97** [comment]
still send the server log

**Comment by Kichura** [comment]
I have already my own solution to this so will close this as a result - forgot to update main comment.
