### ISSUE TITLE
Fabric - 1.19.2 - Ticking Entity (player) crash shortly after joining

### ISSUE THREAD

**Issue by trentnbauer** [Flemmli97/Flan#190]
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

0.60.0+1.19.2

### Mod version

Flan 1.19-1.8.1

### Description

G'day mate,
I'm hoping this is an easy one to sort out but unsure where to go - hopefully the logs provide some useful information.

Essentially, I join the server and shortly after joining it crashes.

EDIT:
I tried increasing "ticksForNextBlock" from 60 to 600 and was able to play on the server without a crash for a significantly longer period of time.
It looks like the crash is related to this?

### Steps to reproduce

1. Join server
2. Wait 30~ seconds
3. Server crashes

### Logs

Crash Report: https://paste.gg/p/anonymous/8ee8c004644a4dec9276f4d6ac784e86
Server logs: https://paste.gg/p/anonymous/4a6d6f20468c43619b4912cd35e112cb
FLAN config: https://paste.gg/p/anonymous/8783b7a400d543da8218bb7a8b4eac09****

**Comment by Flemmli97** [comment]
flan uses fabric-permission api v 0.2 but shoppy has v 0.1. they need to update
