### ISSUE TITLE
[Feature Request]: Allow only specific blocks to be broken within claim

### ISSUE THREAD

**Issue by Krimsar** [Flemmli97/Flan#191]
### Suggestions

If you want to have a tree farm, for example, it would be helpful if you could allow that only logs may be broken within a claim.

### Solution

Implement a list of blocks that are exempt from the the "break" permission.

A different approach could be to allow to set a height limit for a claim / sub-claim and thus allow everything above to be broken.

**Comment by dAKirby309** [comment]
Yes, I came to the Flan GH page just to look for or to make this exact request of being able to do either or both of the following: Specify which blocks to disallow or allow from breaking within a claim/subclaim, and to be able to change the defaultClaimDepth per claim. 

So say for example, you only want someone to use a crops farm within your claim. Well, to do that, you have to allow others to break and place blocks (seeds, in this case). But if they can break or place seeds, they're able to break or place ANY block instead, which is a big limitation. To aid in forcing a player to only break and replant seeds/crops at the crops farm to be able to change the claim depth of the farm area to only 1 or 2 blocks (to ONLY cover the space taken up by the crops), and to force the player to only place/break crops and seeds.

It would be very useful!

The vanilla way around this (but much less perfect and practical, and much more complicated) would be to allow players to place and break blocks within the claim and then set up command blocks to change the player within the claim to Adventure mode and then give the player a hoe or something that can only break crops/seeds, and somehow only let them place seeds/crops, which is FAR from ideal.
