### ISSUE TITLE
Jukebox and Animals in bucket

### ISSUE THREAD

**Issue by Bluyidark** [Flemmli97/Flan#193]
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

Fabric Loader 0.14.9 1.19.2

### Mod version

flan-1.19-1.8.1.1-fabric

### Description

I discovered two bugs in a claimed area:

1. Jukebox is not able to put in or take out music disc even with JUKEBOX enabled. It can only do so when PLACE is enabled too.

2. With BUCKET, ANIMALINTERACT and HURTANIMAL disabled, players can still pick up animals such as cod, salmon, pufferfish, axolotl and tadpole using water bucket, though it shows up as a visual bug where the animal is still there and will only show up when you relog into the world, and the said water bucket will only place water and not spawning animal inside it.

### Steps to reproduce

1. Claime an area
2. Open up claim menu, click into global permission.
3. Enable JUKEBOX, disable BUCKET, ANIMALINTERACT and HURTANIMAL
4. Exit the menu and place down a jukebox in the claimed area, as well as a water pool with axolotl in the pool
5. Type in command "/flan transferClaim Alex"
6. Take a disc and attempt to place it into the jukebox
7. Take a water bucket and attempt to take the axolotl into the bucket
8. Relog in to the world to see if the axolotl is still present

### Logs

No logs available

**Comment by Flemmli97** [comment]
cannot do anything about bucketable mobs. vanilla does the logic also on client side which tbh it shouldn't do
