### ISSUE TITLE
Double Doors can be opened with flan

### ISSUE THREAD

**Issue by haithem2459** [Flemmli97/Flan#196]
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

43.1.47

### Mod version

1.8.1

### Description

Double doors can be opened, one door stays opened while the other is closed.

### Steps to reproduce

1. Step one

### Logs

na

**Comment by Flemmli97** [comment]
no idea what double door thing you mean since that is not a vanilla thing. as such nothing i can do about it
