### ISSUE TITLE
[Bug] Flan menu GUI allows Permission Groups/Usernames containing illegal characters

### ISSUE THREAD

**Issue by amnotbananaama** [Flemmli97/Flan#20]
#### Issue (The better the description the better i can solve the issue):
The anvil GUI with `/flan menu` allows illegal characters for both player usernames and Permission Group names. It appears that the only valid characters for Permission Groups are characters Brigadier [allows in unquoted strings](https://github.com/Mojang/brigadier/blob/559d8f39727e98d374b0726ad88aed9832beee4e/src/main/java/com/mojang/brigadier/StringReader.java#L170L174). Player usernames must follow [the conventions documented](https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames) by Mojang.

The larger issue is the Permission Groups, as players have a general sense what characters are allowed in a username. Permission Groups or usernames containing illegal characters cannot be interacted with via commands, and must be deleted via the GUI.

#### Steps to reproduce:
1. `/flan menu` while inside a claim.
2. Create a new Permission Group, or add a new player to an existing Permission Group
3. Enter at least one invalid character in the anvil GUI (e.g. `U+0020 (SPACE)`, `U+2265 (♥)`, `U+00E1 (á)`)
-> :x: Save the new permission group or username. `/flan group remove <invalid group>` doesn't work.
**Expected Behavior:** Validate the anvil GUI input, and error if it contains illegal characters after submitting.

#### Affected Versions (Latest is NOT a version):

- Minecraft: `1.16.4`
- Fabric: `fabric-api-0.27.1+1.16`
- Flan: `1.2.0`

#### Other Mods (If you think it might be cause of an incompability):
N/A

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE): 
N/A

**Comment by Flemmli97** [comment]
for players it doesnt matter so much cause it will search if that player with that name exist first
