### ISSUE TITLE
cube of annihilation overlap

### ISSUE THREAD

**Issue by ghost** [Flemmli97/Flan#202]
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

fabric 0.14.10 fabric api version 0.64.0

### Mod version

1.8.1.1

### Description

the cube of annihilation from the twilight forest is unable to break blocks when flan is in the server. I believe that the block breaking permissions of the entity version of the cube are being overwritten in some way?

although it works when in someone elses claim, it doesnt work in your own claim or the global server unclaimed.

### Steps to reproduce

1. install twilight forest version 4.2.301 and the correct versions of the mod loader and flan
2. give yourself a cube of annihilation 
3. hold right click and the cube will come out 
4. when it hits blocks it should break them but it doesnt

### Mods that might affect the issue

between twilight forest version 4.2.301 and flan version 1.8.1.1

### Logs

https://paste.gg/p/anonymous/bd76dffe3458467cb5654acde0b05896

**Comment by Flemmli97** [comment]
well. its a bug on their side. they break blocks if the event is cancelled when it should be the other way around
[https://github.com/TeamTwilight/twilightforest-fabric/blob/1.19.x/src/main/java/twilightforest/entity/CubeOfAnnihilation.java#L94](https://github.com/TeamTwilight/twilightforest-fabric/blob/1.19.x/src/main/java/twilightforest/entity/CubeOfAnnihilation.java#L94)
