### ISSUE TITLE
Players can't interact with redstone in a previously claimed area

### ISSUE THREAD

**Issue by autumnly24** [Flemmli97/Flan#206]
### Modloader

Forge

### Minecraft version

1.16.5

### Modloader version

36.2.39

### Mod version

1.7.2

### Description

I claimed an area but allowed players to interact with redstone and buttons inside it as a subclaim, but players still weren't able to use the buttons (even players in my group, co-owners, etc.)

I deleted the claim, and now players get a message saying "Sorry, you can't do that here!" whenever they press the button. I can still access it fine, but it's frustrating and I don't know what to do about it, because everyone needs access to this redstone.

### Steps to reproduce

1. Place a button
2. Create a claim around the button
3. Create a subclaim that encompasses the entire claim
4. Delete the claim

### Logs

https://paste.gg/p/anonymous/3cb168521ba84b969ed981464338b6de

**Comment by Flemmli97** [comment]
make sure you didnt just delete the subclaim only

**Comment by Flemmli97** [comment]
Prob this is also relevant: ac26a4e
Which fixes when in subclaim mode and trying to delete the parent claim it displaying a success despite not doing anything.
1.16 is out of support though so this wont be backported there. (The underlying mechanic didnt change anyway. Just user feedback)
