### ISSUE TITLE
[Feature Request]: Storage Drawers mod compatibility

### ISSUE THREAD

**Issue by SCPRedMage** [Flemmli97/Flan#207]
### Suggestions

Currently, in order to give people permission to take items out of a drawer from the [Storage Drawers mod](https://www.curseforge.com/minecraft/mc-mods/storage-drawers), you need to give them Break permissions (probably because you left click the drawer to do so).

I don't think I need to state why that is undesirable.

It would be preferable if this was its own separate permissions, or handled by OPENCONTAINER.

**Comment by Fiocher** [comment]
+1 Happened, like Mek Bins.
