### ISSUE TITLE
OpenContainers doesn't work.

### ISSUE THREAD

**Issue by IoRyn13** [Flemmli97/Flan#211]
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

1.19.2

### Mod version

flan-1.19.2-1.8.3-forge

### Description

In Global-Permissions, OPENCONTAINER and INTERACTBLOCK are set to false hoping it doesn't allow other players in the claimed blocks to open chests, crafting table and furnace. However, other players can still open them even though there's a red warning that says "Sorry, you can't do that here!"

It's the same with DOOR, FENCEGATE and TRAPDOOR permissions. All is set to false, yet other players besides the owner are able to open them.

Is this a bug? Is there any way to fix this?

### Steps to reproduce

1. In Global-Permissions, set OPENCONTAINER, INTERACTBLOCK, DOOR, FENCEGATE and TRAPDOOR to false.
2. Non co-owner and visitors right-clicks on chests, furnaces, crafting table, doors, fence gates and trapdoor.
3. Items mentioned can still be opened even when permissions are set to false.

### Logs

-

**Comment by Flemmli97** [comment]
you have chisel and bits?

**Comment by IoRyn13** [comment]
> you have chisel and bits?

Yes, I do.

**Comment by Flemmli97** [comment]
see #173

**Comment by IoRyn13** [comment]
> see #173

Thank you!
