### ISSUE TITLE
[Question]: How does customItemPermission work?

### ISSUE THREAD

**Issue by importnil** [Flemmli97/Flan#213]
### Suggestions

Hi,

First, I can't really get this configurable to work. Here's an example:

```
"customItemPermission": [
    "@c:wrenches-INTERACTBLOCK",
    "techreborn:wrench-INTERACTBLOCK",
    "ae2:nether_quartz_wrench-INTERACTBLOCK",
    "ae2:certus_quartz_wrench-INTERACTBLOCK",
    "techreborn:wrench-BREAK",
    "ae2:nether_quartz_wrench-BREAK",
    "ae2:certus_quartz_wrench-BREAK"
  ],
```

Even if permission don't stack, at least one of them should be applied to an item. However, I still can break or interact, e.g. change sides of a block, in a claim with this set.

Secondly, I was wondering if one could make stacked permissions (or just include every permission by specifying a wildcard) for an item in `customItemPermission` at all? Even leaving just one permission, e.g. `-BREAK`, simply doesn't work.

**Comment by Flemmli97** [comment]
see https://github.com/Flemmli97/Flan/issues/203
also an item having multiple permissions doesnt make sense. and break shouldnt be used for that anyway since the `customItemPermission` is for right clicks
