### ISSUE TITLE
[Feature Request]: Add ability to trust specific fake players to claim.

### ISSUE THREAD

**Issue by JustAnotherGhostName** [Flemmli97/Flan#214]
### Suggestions

Change how trusting players work to support trusting fake players to the claim. Say for example you want to trust ONLY a mob masher from Mob Grinding Utilities, you should be able to trust them to the claim with no issues.

Moving above this, it would be even better if you could select which fake player based off of any fake player names detected or from a premade list of fake player names.

**Comment by Flemmli97** [comment]
you can already do that. the permission checks use uuids and fake player also have an uuid. you would just need to find out what uuid they actually have

**Comment by JustAnotherGhostName** [comment]
Then alternatively, could there be a way to obtain a list of fake player names with uuid's that are detected on the server?
