### ISSUE TITLE
Various types of explosives bypass claims.

### ISSUE THREAD

**Issue by JustAnotherGhostName** [Flemmli97/Flan#215]
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

Forge 43.1.55

### Mod version

Flan-1.19.2-1.8.3

### Description

Various types of explosives can interact / damage claims. All of the explosives here are based off what is available in the ATM8 modpack in version 1.0.7, so its easiest to just start up a ATM8 1.0.7 world to reproduce. 

A list of the explosives are as follows.

Thermal Series:
Every type of explosive variant. IE Tectonic Grenade, Tectonic Explosive, Minecraft with Tectonic Explosive. Its not limited to Tectonic, but just any of their explosives. This also includes things like the redstone explosives which provides Redstone power to the nearby blocks. 

FTB Industrial Contraptions:
Nuke (And possibly nuke arrow, haven't tested the arrow)

Industrial Foregoing: Tools:
Infinity Nuke

### Steps to reproduce

1. Create a claim, doesn't matter what type or where, and doesn't matter what configurations you add to the claim.
2. Transfer the claim to someone else so you no longer have permission to interact with it.
3. Place any of the explosives right outside the claim, or throw one of the grenades in the claim.
4. Activate the explosive if needed.
5. The explosion can grief the claimed land.

### Mods that might affect the issue

Thermal Innovation 1.19.2 10.0.0.16:
https://www.curseforge.com/minecraft/mc-mods/thermal-innovation/files/4112132 

FTB Industrial Contraptions 1900.1.7-build.212:
https://www.curseforge.com/minecraft/mc-mods/ftb-industrial-contraptions-forge/files/3907201

Industrial Forgoing 1.19.2-3.3.2.1-3:
https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing/files/4131914 

### Logs

No crash logs or major errors detected.

**Comment by Flemmli97** [comment]
cant do anything about thermal innovation cause its arr but guess the same applies.
but for the other mods:
i simply use the explosion event from forge and since they all use a custom explosion and dont call the event it doesnt work. it should be on them then to either use the event or have compat
