### ISSUE TITLE
Quark block placing completely bypasses claim protection.

### ISSUE THREAD

**Issue by JustAnotherGhostName** [Flemmli97/Flan#216]
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

Forge 43.1.55

### Mod version

Flan-1.19.2-1.8.3

### Description

Quarks feature that lets you place blocks under other blocks when you are not below it bypasses any form of Flan claim protection. This feature is primarily there so you can build staircases going down and things like that, but appears to bypass Flans protection. 

Currently this is tested on a ATM8 1.0.7 server.

### Steps to reproduce

1. Startup a world with quark and flan installed.
2. Build some structure that has some form of over hang.
3. Create a claim with flan including the structure, and transfer it to someone else.
4. While standing on top of the structure, place a block with quark under said structure.
5. Quark bypasses Flan successfully. 

### Mods that might affect the issue

Quark 3.3-377.
https://www.curseforge.com/minecraft/mc-mods/quark/files/4205585

### Logs

No specific logged message noticed.

**Comment by MrJorman** [comment]
This needs to be passed to the Quark developer to add the Flan event mod to the mod .

**Comment by MrJorman** [comment]
The Supplementaries and Quark mod already has support for the Flan mod from a part.

**Comment by MrJorman** [comment]
I asked the developers to do this and they were able to.

**Comment by JustAnotherGhostName** [comment]
Sounds good, ill test once the pack im on updates quark.

**Comment by Flemmli97** [comment]
seems fixed on quark end. reopen if issue persist

**Comment by GitJhopa** [comment]
> seems fixed on quark end. reopen if issue persist

i delete your mod, and install the best Open Parties and Claims. good bye.

**Comment by JustAnotherGhostName** [comment]
Good for you? That mod aint really a competitor per say for flan, more so
ftb chunks / teams, which pretty much any pack has.

Flan imo is more so for people looking for something like grief prevention
or world guard, as it has the ease of gp but configuration of wg.
