### ISSUE TITLE
Dragon eggs can go into claims / admin claims.

### ISSUE THREAD

**Issue by JustAnotherGhostName** [Flemmli97/Flan#218]
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

Forge 43.1.55

### Mod version

Flan-1.19.2-1.8.3

### Description

Dragon eggs can be teleported into a admin claim, and presumably a normal claim by a player. This is particularly an issue in modded where there is more than 1 egg and are craftable. Though this is likely an issue on more vanilla like modpacks with duplication glitches. 

The reason this is more relevant is someone could just have a machine automatically place the dragon egg, and spam right click it to teleport it in theory, effectively griefing an area. 

### Steps to reproduce

1. Make a admin claim / transfer a claim to another player
2. Make sure your not in adminMode
3. Place dragon egg near claim
4. Right click to teleport it until it lands into the claim.
5. In theory, repeat steps 3 and 4 until the claim is completely filled with dragon eggs.

### Logs

No relevant logs.

**Comment by Flemmli97** [comment]
i dont think there is anything i can do about that since the dragon egg teleport has no player context. it doesnt know what player caused it to teleport. i could cancel interactions with dragon eggs if they are in 16 blocks around any claims without permissions but that might be not so performant

**Comment by JustAnotherGhostName** [comment]
That solution likely would work. I'm not personally certain about the performance as I dont specialize in anything related to the Game Development side of programming, but it might be a valid thing to test out?
