### ISSUE TITLE
Players can right click to harvest crops in others claims.

### ISSUE THREAD

**Issue by JustAnotherGhostName** [Flemmli97/Flan#219]
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

Forge 43.1.55

### Mod version

Flan-1.19.2-1.8.3

### Description

My apologies that I dont know specifically what mod in the pack enables right clicking to harvest blocks, but the pack is ATM8 in version 1.0.7. 

The issue specifically is that players are able to right click to harvest players crops when they are fully grown within a flan claim. Notably, this was observed with Mystical Agriculture crops, however, I am assuming other crops work as the right click harvest is not a mystical agriculture specific feature. 

### Steps to reproduce

1. Grow some crops that support right click harvesting (so most vanilla crops, mystical agriculture, or a bunch of other ones)
2. Make sure the grown crop is in a claim that you are not trusted in.
3. Right click harvest said crop.
4. Observe that it says "Sorry you can not do that here" but obtain the dropped crop harvest.

### Mods that might affect the issue

At least mystical agriculture, but pretty much any crop that supports right click to harvest. Again, my apologies but I am uncertain which mod specifically enables right click harvesting. 

### Logs

No specific logs.

**Comment by Flemmli97** [comment]
created new issue. see https://github.com/Nyphet/harvest-with-ease/issues/14
