### ISSUE TITLE
Door Permissions

### ISSUE THREAD

**Issue by Krazytrain** [Flemmli97/Flan#220]
### Modloader

Forge

### Minecraft version

1.16.5

### Modloader version

Forge 36.3.23

### Mod version

Flan 1.7.3 forge

### Description

The door permission does not work if you have double door mod installed at the same time. 

### Steps to reproduce

1. Add Flan and double door mod.
2. claim the land
3. disable the permission for doors
4. others can use the doors still if it's a double door.

### Mods that might affect the issue

Double door forge 1.16.5

### Logs

I dont have logs.

**Comment by Flemmli97** [comment]
since i dont cancel the `RightClickBlock` event but instead use `setUseBlock` they also need to check `getUseBlock`
