### ISSUE TITLE
[BUG] Flan 1.19.2 Fabric The portal to hell ignores the region.

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#222]
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

Fabric

### Mod version

flan-1.19.2-1.8.3-fabric.jar

### Description

The player builds a portal in his region where PVP is turned off, and other players in hell on the other side of the portal shoot arrows from a bow or a distributor into the portal, or call dynamite or crystal ender next to the portal and damage passes through the portal from arrows and explosions ignoring the disabled PVP in the region.

### Steps to reproduce

The player builds a portal in his region where PVP is turned off, and other players in hell on the other side of the portal shoot arrows from a bow or a distributor into the portal, or call dynamite or crystal ender next to the portal and damage passes through the portal from arrows and explosions ignoring the disabled PVP in the region.

### Logs

no logs.

**Comment by Flemmli97** [comment]
well yeah. arrows etc. loose their owner when they go through portals. nothing i can do there
