### ISSUE TITLE
Only one config working :'(

### ISSUE THREAD

**Issue by Wahou5799** [Flemmli97/Flan#225]
### Modloader

Forge

### Minecraft version

1.16.5

### Modloader version

forge 36.2.34

### Mod version

1.16.5 - 1.7.2

### Description

Hi! It seems like nothing work... PPL can open chests, door and place things on claims. The only thing they cant do on claim is breaking stuff... 

I tried many configs to fix this issue but nothing works. What should I do? 

### Steps to reproduce

1. make sure the permission nodes are correctly distributed:
2. heres the config: 
3. {
  "__comment": "For help with the config refer to https://github.com/Flemmli97/Flan/wiki/Config",
  "configVersion": 4,
  "lang": "en_us",
  "startingBlocks": 500,
  "maxClaimBlocks": 5000,
  "ticksForNextBlock": 600,
  "minClaimsize": 20,
  "defaultClaimDepth": 100,
  "maxClaims": -1,
  "defaultClaimName": "",
  "defaultEnterMessage": "",
  "defaultLeaveMessage": "",
  "blacklistedWorlds": [],
  "worldWhitelist": false,
  "claimingItem": "minecraft:golden_hoe",
  "inspectionItem": "minecraft:stick",
  "claimDisplayTime": 1000,
  "permissionLevel": 4,
  "buySellHandler": {
    "buyType": "MONEY",
    "sellType": "MONEY",
    "buyValue": -1.0,
    "sellValue": -1.0,
    "ingredient": []
  },
  "maxBuyBlocks": -1,
  "lenientBlockEntityCheck": false,
  "breakBlockBlacklist": [
    "universal_graves:grave"
  ],
  "interactBlockBlacklist": [
    "universal_graves:grave"
  ],
  "breakBlockEntityTagBlacklist": [],
  "interactBlockEntityTagBlacklist": [
    "IsDeathChest",
    "gunpowder.owner",
    "shop-activated"
  ],
  "ignoredEntities": [
    "corpse:corpse"
  ],
  "entityTagIgnore": [
    "graves.marker"
  ],
  "customItemPermission": [
    "appliedenergistics2:nether_quartz_wrench-INTERACTBLOCK",
    "appliedenergistics2:certus_quartz_wrench-INTERACTBLOCK"
  ],
  "customBlockPermission": [],
  "dropTicks": 6000,
  "inactivityTimeDays": 30,
  "inactivityBlocksMax": 2000,
  "deletePlayerFile": false,
  "bannedDeletionTime": 30,
  "offlineProtectActivation": -1,
  "enableLogs": true,
  "defaultGroups": {
    "Visitor": {
      "BED": true,
      "ENCHANTMENT": true,
      "OPENCONTAINER": false,
      "ITEMFRAMEROTATE": false,
      "PLACE": false,
      "TRADING": true,
      "DOOR": false,
      "PORTAL": true,
      "TRAPDOOR": false,
      "FENCEGATE": false,
      "BREAK": false,
      "PRESSUREPLATE": true,
      "ENDERCHEST": true,
      "BUTTONLEVER": true,
      "INTERACTBLOCK": false
    },
    "Co-Owner": {
      "WATERBORDER": true,
      "ENCHANTMENT": true,
      "REDSTONE": true,
      "ENDERPEARL": true,
      "BUCKET": true,
      "ARMORSTAND": true,
      "DOOR": true,
      "FENCEGATE": true,
      "ANVIL": true,
      "MINECART": true,
      "BREAK": true,
      "CANSTAY": true,
      "PRESSUREPLATE": true,
      "PISTONBORDER": true,
      "LIGHTNING": true,
      "RAID": true,
      "TRADING": true,
      "HURTANIMAL": true,
      "SNOWGOLEM": true,
      "LECTERNTAKE": true,
      "FLIGHT": true,
      "TELEPORT": true,
      "FAKEPLAYER": true,
      "FROSTWALKER": true,
      "INTERACTBLOCK": true,
      "EDITCLAIM": true,
      "ENDERMAN": true,
      "ENDCRYSTALPLACE": true,
      "EDITPOTIONS": true,
      "TARGETBLOCK": true,
      "OPENCONTAINER": false,
      "ITEMFRAMEROTATE": true,
      "BEACON": true,
      "TRAPDOOR": true,
      "DROP": true,
      "PROJECTILES": true,
      "WITHER": true,
      "ANIMALSPAWN": true,
      "CHORUSFRUIT": true,
      "PICKUP": true,
      "BUTTONLEVER": true,
      "NOTEBLOCK": true,
      "EDITPERMS": true,
      "BOAT": true,
      "FIRESPREAD": true,
      "BED": true,
      "BREAKNONLIVING": true,
      "NOHUNGER": true,
      "LOCKITEMS": true,
      "MOBSPAWN": true,
      "PLACE": true,
      "TRAMPLE": true,
      "HURTPLAYER": true,
      "PORTAL": true,
      "EXPLOSIONS": true,
      "ANIMALINTERACT": true,
      "XP": true,
      "ENDERCHEST": true,
      "JUKEBOX": true
    }
  },
  "globalDefaultPerms": {
    "*": {
      "NOHUNGER": "ALLFALSE",
      "LOCKITEMS": "ALLTRUE",
      "FLIGHT": "ALLTRUE",
      "MOBSPAWN": "ALLFALSE",
      "EDITPOTIONS": "ALLFALSE",
      "TELEPORT": "ALLFALSE"
    }
  }
}

### Mods that might affect the issue

Pixelmon is installed. So does travel.jar and cubeengine that seems to interfere.

### Logs

https://gist.github.com/Wahou5799/b3ff827dd4ed9524c26b68af5ab240e6

**Comment by Flemmli97** [comment]
you are using spongeforge so unless you can reproduce this in a pure forge environment this isnt supported
