### ISSUE TITLE
Fires Not Spreading or Extinguishing

### ISSUE THREAD

**Issue by AetheriMC** [Flemmli97/Flan#229]
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

0.14.14

### Mod version

1.8.3

### Description

With FLAN installed, fires both inside and outside of a claim boundary fail to extinguish naturally (either do to rain, time, etc.) and do not spread.

I've tested whether or not this was related to the Gamerule and specifically removed FLAN to determine if this was the issue.

### Steps to reproduce

1. Install Flan
2. Start Fire on burnable surface
3. Fire will neither spread or extinguish

### Logs

https://paste.gg/p/anonymous/229c8eb85858498cbf2bc3936808e953

**Comment by Flemmli97** [comment]
unable to reproduce. make sure you have not changed anything in the config like global permissions that turn off fire completely

**Comment by Flemmli97** [comment]
closing due to this being stale
