### ISSUE TITLE
[Feature Request]: It is very inconvenient to view the list of privates.

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#233]
### Suggestions

It is very inconvenient to view the list of privates. I would like the regions to have names or numbers, like the region that I created first has the name "1" and is assigned to me. So that I can delete it, since some players can accidentally lock the region in a random place and forget it, I want something like / rg list and / rg delete (name)

**Comment by Flemmli97** [comment]
you can already name and rename claims. see the wikifor that. and claim list will also show the name
