### ISSUE TITLE
[1.19.2] CarryOn not respecting Claims

### ISSUE THREAD

**Issue by itsdinkd** [Flemmli97/Flan#235]
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

0.76.0

### Mod version

1.8.4.1

### Description

https://github.com/Tschipp/CarryOn/issues/487

users can enter another players base and pick up their blocks with 0 permission

### Steps to reproduce

1. add carryon mod
2. have another player create claim
3. enter that players claim
4. pick up a chest for example using 

### Mods that might affect the issue

carryon

### Logs

no log

**Comment by Tschipp** [comment]
To add some context: Carry on will send out a BreakEvent before picking up a block. If that event is canceled, the pickup is denied.
Same for placement: it sends an EntityPlaceEvent first. I'm not sure how flan handles permissions, but most other permission mods that I've seen listen to some break events to cancel them on protected land.

**Comment by Flemmli97** [comment]
i cannot reproduce it. i do cancel the breakevent. and this works on my end.
this was tested on the 1.19.4 branch but the code for this part is the same on 1.19.2

https://github.com/Flemmli97/Flan/assets/34157027/9adadc48-d908-4bbd-a0e7-811000c94620

**Comment by itsdinkd** [comment]
It looks like the a new version of carryon "improved protection respection"

- Fixed IMC messages not being sent
**- Now respects protections more**
- Fixed crashes
- Added entries to default blacklist
- Fixed bug where sneaking would conflict with carrying

**Comment by Flemmli97** [comment]
closing this due to stale and resolved?
