### ISSUE TITLE
[Feature Request]: A World Spawn claim

### ISSUE THREAD

**Issue by Chickenooble** [Flemmli97/Flan#237]
### Suggestions

Currently the TP feature allows players to teleport to their own claims, other claims (if the name is known or if the name is known), and admin claims.  It would be nice to allow admins to designate specific admin claims as teleportable by anyone.  The use case would be for specially protected areas that a single player doesn't own -- world spawn locations, a central city, etc.  

Furthermore, perhaps separate these designated claimed into a "World" category.

So /tp would show Admin, Other, Self, and World.  World would show the Admin Claims designated as World claims.

**Comment by PoolloverNathan** [comment]
> other claims (if the name is known or if the name is known)

Did you make a typo here?

**Comment by Flemmli97** [comment]
if the claim allows teleportation then it doesnt matter if its an admin claim or not. if you want players to teleport to those claims simply allow tp for those players in the admin claim.

having a world option is redundant as admin does that already. i now did rename admin to global to be more user friendly
