### ISSUE TITLE
Building Gadgets Bypasses FLAN

### ISSUE THREAD

**Issue by Solidrockkarter** [Flemmli97/Flan#239]
### Modloader

Forge

### Minecraft version

1.18.2

### Modloader version

40.2.1

### Mod version

1.8.4

### Description

Using building gadgets in an area where you don’t have permissions works

### Steps to reproduce

1. Go to an area that you don’t have permissions in
2. Use either the buildinggadgets:gadget_building OR buildinggadgets:gadget_copy_paste

### Mods that might affect the issue

Building gadgets DireWolf20

### Logs

?

**Comment by Flemmli97** [comment]
note that copy and paste gadget is not covered since building gadget seem to not check/use any forge events there
