### ISSUE TITLE
Bug with multistructural mechanisms

### ISSUE THREAD

**Issue by TheKlimoT** [Flemmli97/Flan#241]
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

Forge

### Mod version

flan-1.19.2-1.8.4-forge

### Description

In the ic2 classic 1.19.2 mod, there are multistructural mechanisms, 1 block cannot be opened, but the rest open freely.

### Steps to reproduce

1. Privatize the territory
2. Build a multistructural mechanism
3. Try to open any other block

### Mods that might affect the issue

No response

### Logs

No crash logs.

**Comment by TheKlimoT** [comment]
https://youtu.be/rsZm8P6O1kE - video bug

**Comment by Flemmli97** [comment]
the mod is arr and closed source. (the github repo only contains the api). so nothing i can do about that.
its also 1.19.2 and that is out of support too here
