### ISSUE TITLE
Creepers, dynamites, ender crystals can cause damage to players

### ISSUE THREAD

**Issue by GitJhopa** [Flemmli97/Flan#242]
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

Forge

### Mod version

flan-1.19.2-1.8.4-forge

### Description

Creepers, dynamites, ender crystals can cause damage to players, animals, armor stands, frames in someone else's private, if you drop them in private or blow up with the border of it. Please correct!!!

### Steps to reproduce

Creepers, dynamites, ender crystals can cause damage to players, animals, armor stands, frames in someone else's private, if you drop them in private or blow up with the border of it. Please correct!!!

### Logs

no logs.

**Comment by Flemmli97** [comment]
Creepers: wont fix. This mod is not meant for protection against mobs
Dynamites: This is not vanilla so if you want a fix you would need to provide the mod first
For ender crystals see #221

**Comment by Flemmli97** [comment]
closing this since there is no further response
