### ISSUE TITLE
Flan causes the server to crash

### ISSUE THREAD

**Issue by At87668** [Flemmli97/Flan#246]
### Modloader

Forge

### Minecraft version

1.16.5

### Modloader version

36.2.39

### Mod version

1.7.2

### Description

When the player holds the gold hoe ,server to crash!

Mod List :

additional-guns-0.8.0-1.16.5
cfm-7.0.0pre22-1.16.3
cgm-1.2.6-1.16.5
citadel-1.8.1-1.16.5
CoroUtil-1.16.5-1.2.37
curios-forge-1.16.5-4.0.5.1
diet-forge-1.16.5-1.0.4.0
DynamicTrees-1.16.5-0.10.5
ferritecore-2.1.1-forge
flan-1.16.5-1.7.2-forge
iceandfire-2.1.12-1.16.5
Iceberg-1.16.5-1.0.45
infernalmobs-1.16.2.1
inzheFoPCore-v.1.2.0
ironchest-1.16.5-11.2.13
jei-1.16.5-7.7.1.153
lazydfu-0.1.3
lootbeams-1.16.5-release-july1722
Mantle-1.16.5-1.6.157
Mekanism-1.16.5-10.1.2.457
MekanismAdditions-1.16.5-10.1.2.457
MekanismGenerators-1.16.5-10.1.2.457
MekanismMatter-1.20.1-Beta-1.16.5
notreepunching-forge-1.16.5-4.3.0
obfuscate-0.6.3-1.16.5
Project_MMO-1.16.5-3.69.0
RoadRunner-mc1.16.5-1.4.1
SereneSeasons-1.16.5-4.0.1.129-universal
SpartanShields-1.16.5-2.1.2
spartantwilight-1.16.5-2.3.2
SpartanWeaponry-1.16.5-2.2.0-rc-2
swiaf-1.16.5-1.1.2
ToughAsNails-1.16.5-4.1.0.9-universal
twilightforest-1.16.5-4.0.546-universal
zombieawareness-1.16.5-1.12
zombieawarenessfix-1.1

### Steps to reproduce

1. Add Mods from the List
2. Start Server
3. Join the Server
4. Pull out a Gold Hoe
5. Server to Crash

### Mods that might affect the issue

I don't kown.

### Logs

https://paste.gg/p/anonymous/1711ed24929840f9ae6d6aa6c8a8c8de

**Comment by Flemmli97** [comment]
your lang file is incorrect. specifically the `claimBlocksFormat`. it has no 4th argument in 1.16 but you have it in your lang
