### ISSUE TITLE
Mod overloading the config file

### ISSUE THREAD

**Issue by ItsTeraBytes** [Flemmli97/Flan#248]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

0.14.21

### Mod version

1.20.1-1.8.6

### Description

Just recently I restarted my MC server to test a new mod. To my surprise, the server didn't start. So I read the crash report and saw the flan mod had some issues with the config file. I opened the config file and waited, then my text editor crashed. I was even more surprised when I checked the file and found out it took 896 MB of storage! So I downloaded the file and used my own text editor. I was shocked when the array "customBlockPermission" and "customEntityPermission" had 33,554,432 lines all with the text "taterzen:npc-TRADING". I also don't have the Taterzens mod installed. I've attached a screenshot showing this and the config file.
![Code_oWmL4tFVGY](https://github.com/Flemmli97/Flan/assets/88017555/16d176eb-395c-413d-b2ad-588cd2e3214e)

### Steps to reproduce

1. Put the mod in a fabric server (It might work on forge, didn't test if it works there)
2. Open "flan_config.json" and check either "customBlockPermission" or "customEntityPermission" has "taterzen:npc-TRADING" as one of its entries. (At least 1 of them needs to have "taterzen:npc-TRADING" for it to work)
3. Start the server
4. Run the command "/flan reload" or restart the server
5. Open "flan_config.json" and see that both "customBlockPermission" and "customEntityPermission" now have  "taterzen:npc-TRADING"
6. Repeat steps 4 and 5. The more you reload the more entries it makes as it's exponential. (i.e 1 reload makes 2 entries, 2 reloads makes 4 entries, 3 reloads makes 8 entries, and so on)
7. After about 24 reloads, if you try to start the server it will not start as there are 33,554,432 "taterzen:npc-TRADING" entries.

### Mods that might affect the issue

None

### Logs

https://gist.github.com/ItsTeraBytes/6d338fd2d0879cb15b92753e31e89195

**Comment by kittech0** [comment]
The issue wasnt fixed @Flemmli97

**Comment by ItsTeraBytes** [comment]
> The issue wasnt fixed @Flemmli97

Fixed for me. It doesn't spam the config file anymore
