### ISSUE TITLE
Crash on world creation

### ISSUE THREAD

**Issue by Moosheking** [Flemmli97/Flan#249]
### Modloader

Fabric

### Minecraft version

1.20.1 

### Modloader version

0.86.1 

### Mod version

1.8.6 

### Description

Crash on world creation 

### Steps to reproduce

Create World 

### Mods that might affect the issue

Unknown  

### Logs

https://gist.github.com/Moosheking/9cf58dfc473772521e820c545e9bbc37

**Comment by Flemmli97** [comment]
dupe of #248
