### ISSUE TITLE
Trading doesn't work

### ISSUE THREAD

**Issue by ItsTeraBytes** [Flemmli97/Flan#251]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

0.14.21

### Mod version

1.20.1-1.8.6

### Description

I have a librarian villager on a server and for some reason, my players cannot use him while he is in the claim. Outside is fine but the inside is not. "Trading" is allowed at the global permissions and still doesn't work. I even gave my alt every permissions possible but still not allowed to be traded.

### Steps to reproduce

1. Get a villager
2. Get another player or alt account
3. Try to trade (You shouldn't be able to)
4. Give "Trading" permission
5. Try step 3 again

### Mods that might affect the issue

Not that I know of. None of my mods affect the flan mod (Except for better harvesting) or villagers.

### Logs

The logs showed nothing special when testing but sure
https://gist.github.com/ItsTeraBytes/53022fcb74e61632e6e2068f6717eb9e

**Comment by Flemmli97** [comment]
show your config
