### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by Zunwolf1896** [Flemmli97/Flan#258]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

0.87.0+1.20.1

### Mod version

1.20.1-1.8.7

### Description

The config has a rediculous amount of "taterzen:NPC-TRADING" lines. 

![image](https://github.com/Flemmli97/Flan/assets/88537204/3bcb2396-9433-4416-9d9a-4ec15fd6db46)

### Steps to reproduce

1. Download Mod
2. Open Config to make some changes
3. Find over 131070 lines of the same thing repeated.

### Logs

No logs, was just the congig. No errors or anything.

**Comment by Flemmli97** [comment]
delete the config and let it regenerate. if you had a previous version already installed this bug was in it but its fixed in 1.8.7
