### ISSUE TITLE
[Feature request] Even more in-depth permissions

### ISSUE THREAD

**Issue by CodedSakura** [Flemmli97/Flan#26]
It would be useful to have specific permissions for:
- using an enderchest
- using an enchantment table
- extending a piston over the claim border
- letting water flow over the claim border

I think there was something else about the claim border that'd be nice to have be toggle-able

**Comment by Flemmli97** [comment]
enderchest and enchantment table arent included because they either dont have inventory or are player bound and do nothing to the terrain even if used. same with things like stone cutter, crafting table etc.

**Comment by CodedSakura** [comment]
well i'd like to be able to give anyone in my claim to use the enderchests, while not having access to regular chests.
about the enchantment table, i would like to have the ability to prevent others from using it in my base, but allow the use of it in a XP grinder

**Comment by Flemmli97** [comment]
hmm i just see that enderchest is actually a blockentity so they are now blocked from using.
