### ISSUE TITLE
[Feature Request]: Please make 1.19.2 Forge with the latest updates.

### ISSUE THREAD

**Issue by GitJhopa** [Flemmli97/Flan#260]
### Suggestions

I really need your mod, please update for 1.19.2 Forge, since all the main mods are there. Thank you!

**Comment by Flemmli97** [comment]
sorry but no. 1.19.4 is supported. 
else there are too many mc versions to support. cant do them all

**Comment by GitJhopa** [comment]
> sorry but no. 1.19.4 is supported. else there are too many mc versions to support. cant do them all

Yep, thank you very much! I took a broken mod for 1.19.2, there are a lot of bugs and errors, but of course you don’t want to port it, because 1.19.4 is such a cool version that has no mods and hasn’t given in to anyone!

**Comment by GitJhopa** [comment]
I left you a ticket about an error in opening doors from the Quark mod (tweak: double door opening), also multi-structure blocks from the IC2 Classic mod can be opened in foreign regions, Permissions through Luckperms for issuing more private blocks and the number of privates do not work.

**Comment by GitJhopa** [comment]
Excuse me, but to any of my tickets you respond like this:

If you don’t know how to do this, check out the Open Parties And Claims mod from Xaero and see how its code is made for certain things.

![image](https://github.com/Flemmli97/Flan/assets/86250668/2973ce5f-1996-4fea-8640-58c7aa9594d6)

**Comment by Flemmli97** [comment]
dude. end crystals do NOT know who blew them up. open claims instead simply blocks every explosion damage which is not what i want
