### ISSUE TITLE
Eating in another player's land is blocked

### ISSUE THREAD

**Issue by BlasterM5** [Flemmli97/Flan#263]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

0.90.7

### Mod version

1.8.8

### Description

Eating in another user's land is blocked for some reason, and I can't find a permission that would block it.

### Steps to reproduce

1. Make Claim
2. Bring another player into claim
3. Have player eat
4. Watch other player be sad their food disappears, but it says they're blocked from performing the action and they're still hungry

### Logs

No server log data pertains to this issue

**Comment by Flemmli97** [comment]
tested and cant reproduce. and even if its blocked the item should not disappear.
did both cases of
1. looking into air while eating
2. looking at a block while eating which should show the message but not prevent eating

**Comment by Flemmli97** [comment]
closing due to this being stale
