### ISSUE TITLE
[Feature Request]: Is there any ingame map that support flan?

### ISSUE THREAD

**Issue by mikaba-eu** [Flemmli97/Flan#265]
### Suggestions

Hi, I tried [JourneyMap](https://www.curseforge.com/minecraft/mc-mods/journeymap) and [Xaero's World Map](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map). And both don't show the claim ingame. Do I need some extra mod for this? Or is that just not implemented?

**Comment by ShelLuser** [comment]
Just a fellow user here; anyway, Xaero only shows (user)claims from its own [Open Parties & Claims](https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims) mod, but _nothing_ else. So even if you set up something with WorldGuard then it wouldn't show up (unless said 'parties & claims' can pick that up). Hence my conclusion that FLAN isn't going to work for this (I'm also use Xaero btw).

Hope this can help!

**Comment by Flemmli97** [comment]
journeymap has an api but its client side only.
xaero is closed source and arr so cant support that.
if you have any other feel free to share them here and ill see

**Comment by Flemmli97** [comment]
closing this now. if a map that also has a server side component is found feel free to create a feature request for that

**Comment by mysticdrew** [comment]
Journeymap dev here,  if you decide to add support or need help adding integration. Feel free to reach out, our client api can easily support displaying claims. 

If you need server side support.  We can chat
