### ISSUE TITLE
flan doesnt add minecolonies claims to the personal claim blocks

### ISSUE THREAD

**Issue by GulliUlli** [Flemmli97/Flan#266]
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

43.3.5

### Mod version

1.8.3

### Description

i have a big colonie with a lot of claim area, but if i look at flan, i have used 0/5000 blocks for claiming, but minecolonies integration is enabled.

### Steps to reproduce

1. build a colonie
2. check your claimcount

### Logs

not exist

**Comment by Flemmli97** [comment]
the integration just makes it so you cant claim over mine colonies claims. nothing else

**Comment by GulliUlli** [comment]
oooh okey i understand^^ thx :)
