### ISSUE TITLE
Modrinth.com missing all 1.19.2 versions

### ISSUE THREAD

**Issue by maiguel5** [Flemmli97/Flan#270]
### Modloader

Fabric and Forge

### Minecraft version

1.19.2

### Modloader version

fabricloader 0.14.24 or similar

### Mod version

Any 1.19.2

### Description

https://modrinth.com/mod/flan/versions have 0 versions to 1.19.2

### Steps to reproduce

Go to https://modrinth.com/mod/flan/version

### Mods that might affect the issue

None

### Logs

None

**Comment by Flemmli97** [comment]
use curseforge for that
