### ISSUE TITLE
[Feature Request]: add/remove claim blocks

### ISSUE THREAD

**Issue by Jaackla** [Flemmli97/Flan#271]
### Suggestions

could you add in the future admin commands that could be like /flan removebonusclaimblocks (name) (amount) and /flan remove claimblocks (name) (amount). Also when players sell blocks it comes from the bonus claim blocks, could it be that it uses standard and bonus combined so if i had 1k normal and 1k bonus and i sold 1.5k it would take the bonus claim blocks first then take 500 from my regular

**Comment by Flemmli97** [comment]
sell/buy will stay as bonus claim blocks. having it use normal claim blocks is will make it so you can infinitly sell claim blocks which if you have an economy just... provide that passive income somewhere else
