### ISSUE TITLE
[Feature Request]: ADD SUPPORT 1.19.2 FORGE!! 

### ISSUE THREAD

**Issue by kitovoi111** [Flemmli97/Flan#273]
### Suggestions

[Feature Request]: ADD SUPPORT 1.19.2 FORGE!!

**Comment by kitovoi111** [comment]
New update version NEED FORGE 1.19.2 !! and add support LuckPerms !

**Comment by Flemmli97** [comment]
there is a 1.19.2 version on curseforge. but 1.19.2 itself is not supported anymore. aka no more updates
