### ISSUE TITLE
certain claims won't extend down to bedrock, while others will 

### ISSUE THREAD

**Issue by absurditytxt** [Flemmli97/Flan#274]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

0.14.24

### Mod version

1.8.11

### Description

a player (a) claimed an area (an entire vanilla ocean monument, if that's relevant). they (a) swam vertically downwards, and within a few blocks the "leaving claim area" message popped up. the player (a) had enough claim blocks to cover the claim area (along the horizontal axes). the player (a) has tried deleting and reclaiming the problem area, but the issue still persists. the player (a) has other claims that go down to bedrock perfectly.

another player (b) is also experiencing a similar issue, where their claim is also not extending down to bedrock. the only difference is that they (b) are not claiming an area that contains a world-generated structure. the player (b) also has enough claim blocks to cover the claim area (along the horizontal axes). the player (b) has also tried deleting and reclaiming the problem area, but the issue still persists. the player (b) also has other claims that go down to bedrock perfectly.

lastly, a third player (c) also randomly experiences times where their (c) claims will not go down to bedrock. however, deleting and reclaiming the problem area has solved the issue for them (c) every time it has happened. 

so sorry to bother you, and thank you very much for your time!

### Steps to reproduce

Sorry, but we're unsure how to reproduce the issue, as we don't know why it only affects certain areas, and we also don't know why deleting and reclaiming fixes for the issue for some players but not others.

### Mods that might affect the issue

Not any particular mod, but if it helps, the server revolves around the Origins mod, and we also probably have most performance optimisation mods in because we have a lot of performance issues (lag, tps, etc).

### Logs

No crashing, so no relevant logs?

**Comment by Flemmli97** [comment]
claims dont go to bedrock by default. the claims only go to the y value you are claiming from. if you build below they will then auto extend downwards

**Comment by Flemmli97** [comment]
closing this. create a new issue if something new happens regarding this problem
