### ISSUE TITLE
Regions of players who have not logged in for more than 7-14 days are not deleted, as specified in the flan config.

### ISSUE THREAD

**Issue by kitovoi111** [Flemmli97/Flan#278]
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

Forge

### Mod version

flan-1.19.2-1.8.4-forge.jar

### Description

Regions of players who have not logged in for more than 7-14 days are not deleted, as specified in the flan config.
When I click feather to check the region it shows that the region belongs to <UNKNOWN>

![image](https://github.com/Flemmli97/Flan/assets/147491823/6f9501d8-a825-4f08-bcba-b54093129bb5)

### Steps to reproduce

Config: 
[flan_config.json](https://github.com/Flemmli97/Flan/files/14546760/flan_config.json)

### Logs

[latest.log](https://github.com/Flemmli97/Flan/files/14546763/latest.log)

**Comment by Flemmli97** [comment]
how many claim blocks do they have? at a certain amount they will not be deleted

**Comment by kitovoi111** [comment]
> how many claim blocks do they have? at a certain amount they will not be deleted

5000 blocks

**Comment by kitovoi111** [comment]
[flan_config.json](https://github.com/Flemmli97/Flan/files/14891801/flan_config.json)

**Comment by Flemmli97** [comment]
i mean yeah. you have inactivityBlocksMax set to 5000 they dont get deleted

**Comment by kitovoi111** [comment]
> i mean yeah. you have inactivityBlocksMax set to 5000 they dont get deleted

How many times do you need to specify for them to be deleted?

**Comment by Flemmli97** [comment]
if you want them to always be deleted set it to some number players wont reach

**Comment by Flemmli97** [comment]
closing since it seems resolved
