### ISSUE TITLE
BetterSignsAndFrames compability

### ISSUE THREAD

**Issue by CodedSakura** [Flemmli97/Flan#28]
It seems that the [BetterSignsAndFrames](https://github.com/Ivan0xFF/BetterSignsAndFrames) mod has the ability to edit signs even within claimed areas, as well as allows opening chests through item frames.
I'd like to see some compatibility between the two mods, and I've already opened an issue on their GH (https://github.com/Ivan0xFF/BetterSignsAndFrames/issues/6)

**Comment by Flemmli97** [comment]
that should be on them to add compability since they modify right click behaviour on sign. i could add a sign check on my callbacks but then it would depend on the fabric callback order and then the result is a might work or not situation

**Comment by Jarva** [comment]
Addressed in https://github.com/Ivan0xFF/BetterSignsAndFrames/pull/20
