### ISSUE TITLE
[Feature Request]: Making BuiltinRegistries.register public

### ISSUE THREAD

**Issue by Emafire003** [Flemmli97/Flan#284]
### Suggestions

I would suggest making the registering methods for new permissions public so other mods depending on Flan can simply use those to add new permissions instead of using their own datagen and registering.

**Comment by Flemmli97** [comment]
you dont register your permissions via code anymore. you create a datapack and that registers them.
`BuiltinRegistries.register` is purely for this mods datagen calling that will do nothing unless you use the datagen from this mod. and then you would also generate all permissions from this mod making lot of redundant things.

you can extend `ClaimPermissionProvider` to make a custom datagenerator

**Comment by Emafire003** [comment]
Yeah sorry I misinterpreted the thing, and meant to close this issue already but forgot!
