### ISSUE TITLE
Error Add player to claim

### ISSUE THREAD

**Issue by mghunter59** [Flemmli97/Flan#285]
### Modloader

Forge

### Minecraft version

1.20.1

### Modloader version

Forge 1.20.1-47.2.16

### Mod version

flan-1.20.1-1.10.0-forge

### Description

The interface does not open when I want to add a player to claim

### Steps to reproduce

1. Create claims
2. Open gui /flan menu
3. Click Edit Permissiongroups
4. Click Visitor
5. Click Add

### Logs

https://paste.gg/p/anonymous/fe53065cf8694b6c9885bd9c72c4b467

**Comment by Flemmli97** [comment]
sorry but hybrid servers are not supported. if you manage to reproduce this on a plain forge server feel free to create a new issue with it
