### ISSUE TITLE
Confict with Mod Amendments

### ISSUE THREAD

**Issue by farlydapamanis** [Flemmli97/Flan#286]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

Fabric Loader 0.15.10

### Mod version

Flan 1.20.1-1.10.0

### Description

Server shutdown when claim a land

### Steps to reproduce

1. Step one: Using golden hoe, right click the block for claim

### Logs

https://paste.gg/p/anonymous/492e12812fe24adc9545ba5673dcb105

**Comment by AspectofHope** [comment]
I would like to add that Forge version also has conflicts, placing carpets or candles was crashing our server.

**Comment by Flemmli97** [comment]
> I would like to add that Forge version also has conflicts, placing carpets or candles was crashing our server.

dont hijack other issue reports. make your own issue report

**Comment by Flemmli97** [comment]
> ### Modloader
> Fabric
> 
> ### Minecraft version
> 1.20.1
> 
> ### Modloader version
> Fabric Loader 0.15.10
> 
> ### Mod version
> Flan 1.20.1-1.10.0
> 
> ### Description
> Server shutdown when claim a land
> 
> ### Steps to reproduce
> 1. Step one: Using golden hoe, right click the block for claim
> 
> ### Mods that might affect the issue
> _No response_
> 
> ### Logs
> https://paste.gg/p/anonymous/492e12812fe24adc9545ba5673dcb105

yes version 1.10 has a breaking change which mods depending on flan need to resolve. report it to them. the changelog has a guide for what to change
