### ISSUE TITLE
Placing a block in claim crashed server

### ISSUE THREAD

**Issue by Zunwolf1896** [Flemmli97/Flan#287]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

0.92.1+1.20.1

### Mod version

1.20.1-1.10.0

### Description

Made a claim, set it to Admin claim and started placing blocks for a build - I deleted some grass blocks and went to place an Oak Plank, soon as I right clicked with the plank the server crashed. 

### Steps to reproduce

1. Load up brand new world with flan and other mods
2. Use the /flan adminmode command, then make yourself a claim. 
3. Set up group permessions for that claim, allowing fro flan perm changes, interact, item break and place
4. Decide to increase the pathway and start breaking blocks
5. place a block
6. Server shuts down

### Mods that might affect the issue

Honestly I have no idea, I am using the mods from my [modpack](https://legacy.curseforge.com/minecraft/modpacks/wolfqueens-origins) as well as Luckperms but I have used luckperms with flan for years and this has not been an issue. 

### Logs

https://mclo.gs/4xjsvHb

**Comment by Flemmli97** [comment]
see https://github.com/Flemmli97/Flan/issues/286#issuecomment-2106305810
