### ISSUE TITLE
The Mobspawn option causes the world not to refresh monsters

### ISSUE THREAD

**Issue by MuRaSameee-L** [Flemmli97/Flan#288]
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

forge 43.2.21

### Mod version

1.8.4

### Description

When Mobspawn is changed to "ALLTRUE", monsters will not regenerate even outside the claim

### Steps to reproduce

Mobspawn changed to ALLTRUE in config

### Logs

N/A

**Comment by Flemmli97** [comment]
yes. thats the point. a global permission applies globally. if you dont want that dont set it to that value
