### ISSUE TITLE
Conflicts with quark module functions. Causes functions such as right-clicking to harvest crops to fail

### ISSUE THREAD

**Issue by ASHISK404** [Flemmli97/Flan#289]
### Modloader

Forge

### Minecraft version

1.20.1

### Modloader version

forge

### Mod version

flan-1.20.1-1.10.0-forge

### Description

Conflicts with quark module functions. Causes functions such as right-clicking to harvest crops to fail.
On the server it is also possible to crash with quark
All of this has been tested on both the client and server, and removing the mod-connector would cause the same problem.
PermissionRegistry seems to be the cause of this problem

### Steps to reproduce

1. Step one

### Mods that might affect the issue

Quark-4.0-443.jar  https://modrinth.com/mod/quark/version/1.20.1-4.0-443
Zeta-1.0-16.jar  https://modrinth.com/mod/zeta/version/1.20.1-1.0-16

### Logs

https://gist.github.com/ASHISK404/1888cc100f8029d10d610ec56547bb49

**Comment by Flemmli97** [comment]
see https://github.com/Flemmli97/Flan/issues/286#issuecomment-2106305810. quark needs to update the integration
