### ISSUE TITLE
Death Resets Claim Size

### ISSUE THREAD

**Issue by mahjerion** [Flemmli97/Flan#29]
#### Issue (The better the description the better i can solve the issue):
Upon death, players seem to report that their claim size is resetting back to the starting value. I have players start with 1000 blocks, up to 10000 blocks as a max. But dying sets it back to 1000.

#### Steps to reproduce:
Gain blocks.
Die.
Lose blocks.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.2
- Fabric: 0.10.8
- Flan: 1.2.1

#### Other Mods (If you think it might be cause of an incompability):
Main mods used in the pack are Age of Exile, Charm, Allure, VanillaDeathChests, that may affect it?

**Comment by Flemmli97** [comment]
thank you. i encountered this multiple times but didnt know the cause.
