### ISSUE TITLE
Text is not displayed correctly, cant find specified file.

### ISSUE THREAD

**Issue by kirarcangell** [Flemmli97/Flan#291]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

qfapi 0.91.0

### Mod version

1.10.0

### Description

The mod works perfectly but the only problem is the text is weird, i cant see if a flag its already enabled or anything.

![image](https://github.com/Flemmli97/Flan/assets/157147879/73dead7d-1370-4af2-b26c-ef5608d53889)
![image](https://github.com/Flemmli97/Flan/assets/157147879/71bd51aa-a1e6-47a6-bd94-cda12dcea50a)
![image](https://github.com/Flemmli97/Flan/assets/157147879/44f8c292-d690-42e4-ab07-d1493df8ba0b)

### Steps to reproduce

1. Just install the mod on server, also happens if installed on both client and server.

### Mods that might affect the issue

Using Quilt not fabric.

### Logs

https://paste.gg/p/anonymous/aa1f0108c24741dba3a2ea76fb1ee1c9/files/6178c77cb73e4b25b23d255c7af4bee7/raw

**Comment by Flemmli97** [comment]
ye. its some stuff with quilt which is not supported

**Comment by kirarcangell** [comment]
No problem then. thanks

Switched to fabric, text working perfectly.
