### ISSUE TITLE
Flan is causing my ticks to spike like crazy

### ISSUE THREAD

**Issue by ghost** [Flemmli97/Flan#298]
### Modloader

Forge

### Minecraft version

1.20.1

### Modloader version

Fabric

### Mod version

1.10.4

### Description

Flan is making my MSPT spike up to the 1700s and thus lag the server. Has something to do with player claim data.
https://spark.lucko.me/58af6zQIAK

### Steps to reproduce

Just have flan installed

### Logs

https://spark.lucko.me/58af6zQIAK

**Comment by ghost** [comment]
Also makes the server not stop completely ^ Has an unsafe park in the spark profiler report.

**Comment by Flemmli97** [comment]
added some changes there. please make a new issue if its still a problem
