### ISSUE TITLE
1.10.4 Flan fabric mc 1.20.1 issue

### ISSUE THREAD

**Issue by jbreadtoasted** [Flemmli97/Flan#299]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

0.15.11

### Mod version

1.10.4

### Description

Stating something about an autheserver issue and datapack issue

### Steps to reproduce

1. Loading the server up with the mod installed

### Logs

https://paste.gg/p/anonymous/83a81a5ca0e545dc90b1738e87577a55

**Comment by Flemmli97** [comment]
flan is incompatible with whatever banner is doing. 
they outright replace various stuff.
so use one of them.
