### ISSUE TITLE
The ban on using enchanting_table applies worldwide, even where there is no region

### ISSUE THREAD

**Issue by kitovoi111** [Flemmli97/Flan#301]
### Modloader

Fabric

### Minecraft version

1.20.6

### Modloader version

Fabric

### Mod version

flan-1.20.6-1.10.4-fabric.jar

### Description

The ban on using enchanting_table applies worldwide, even where there is no region

### Steps to reproduce

1. Place enchanting_table
2. Use in config 
3. YOU CANNOT OPEN AN ENCHANTING TABLE EVEN WHERE THERE IS NO REGION

"globalDefaultPerms": {
    "*": {
	  "flan:enchantment": "FALSE",
	  ....

### Logs

no error log

**Comment by Flemmli97** [comment]
yes. thats intended and how global permissions work. setting it to false disables it everywhere. and you can change it in a claim
