### ISSUE TITLE
Server crash upon entering a claim area with an invalid text-type claimMessage

### ISSUE THREAD

**Issue by rhocairn** [Flemmli97/Flan#305]
### Modloader

Fabric

### Minecraft version

1.21

### Modloader version

fabric-server-1.21-0.15.11.jar // fabric-api-0.100.3+1.21.jar

### Mod version

flan-1.21-1.10.5-fabric.jar

### Description

After creating an admin claim with an invalid claimMessage "text" type, the server crashes upon a player entering that claim with exception `java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null`

I couldn't find the documentation on the claimMessage command at all, but I'm guessing the "text" type is actually a key for a lang file? And "message" type is actually plain text?

### Steps to reproduce

1. Create an admin claim (possibly any claim will do)
2. Within that claim, run `/flan claimMessage enter title text "Test"`
3. Exit and re-enter the claimed zone
4. Server crash

### Logs

https://paste.gg/p/anonymous/a4521d2579d44c0c8976b8cc5aa6db5f

**Comment by Flemmli97** [comment]
update the mod
