### ISSUE TITLE
[NeoForge1.21][Loading Crash][LivingDamageEvent]

### ISSUE THREAD

**Issue by ootwclyhe** [Flemmli97/Flan#306]
### Modloader

Forge

### Minecraft version

1.21

### Modloader version

NeoForge: 21.0.40-beta

### Mod version

Mod Version: 1.21-1.10.6

### Description

> -- MOD flan --
Details:
        Mod File: /D:/ALL/game/MineCraft/21/mods/flan-1.21-1.10.6-neoforge.jar
        Failure message: fml.modloading.failedtoloadmod
        Mod Version: 1.21-1.10.6
        Mod Issue URL: https://github.com/Flemmli97/Flan/issues
        Exception message: java.lang.IllegalArgumentException: Cannot register listeners for abstract class net.neoforged.neoforge.event.entity.living.LivingDamageEvent. Register a listener to one of its subclasses instead!

### Steps to reproduce

1. install neoforge server
2. add it to mods folder
3. run start cmd
4. then crash

### Mods that might affect the issue

- Healing Campfire (healingcampfire) has failed to load correctly
          java.util.ServiceConfigurationError: com.natamus.collective_common_neoforge.services.helpers.ToolFunctionsHelper: Provider com.natamus.collective.neoforge.services.NeoForgeToolFunctionsHelper could not be instantiated
        - Collective (collective) has failed to load correctly
          java.lang.NoClassDefFoundError: Could not initialize class com.natamus.collective_common_neoforge.services.Services
        - Flan (flan) has failed to load correctly
          java.lang.IllegalArgumentException: Cannot register listeners for abstract class net.neoforged.neoforge.event.entity.living.LivingDamageEvent. Register a listener to one of its subclasses instead!
        - Infernal Mobs (infernalmobs) has failed to load correctly
          java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/entity/living/LivingHurtEvent

### Logs

<script src="https://gist.github.com/ootwclyhe/5ab651510c261716dcb7cc2dd1521244.js"></script>

**Comment by Flemmli97** [comment]
fixed in #309
