### ISSUE TITLE
Amendments causes crash with Flan due to carpetblocks and skulls.

### ISSUE THREAD

**Issue by qqbone** [Flemmli97/Flan#319]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

Fabric - 0.15.11

### Mod version

flan-1.20.1-1.10.6-fabric

### Description

Issue has been fixed as due to modpack running outdated version of Amendments. 

Had to replace a carpet block and after installing and setting up flan, server exploded, made another claim and tested again. Tested in or out of a claim.

If carpet is held in hand and interacted with container it will crash, but will not crash in item frame.

Also happens with Pepple's chest shop, but they have an updated version that's compatible.

### Steps to reproduce

1. Get a carpet colour of your choice
2. Place anywhere.
3. Server go boom.

### Mods that might affect the issue

It's the amendments mod, due to some vanilla features I guess. It adds carpets to stairs. Carpet blocks will crash along any modded carpets that can be compatible with its feature. Out of all the mod's features the only two that have an issue are skulls and carpets. Cannot test the skull candle feature due to skulls not working. 

https://www.curseforge.com/minecraft/mc-mods/amendments 

### Logs

https://pastebin.com/4DTAPmb3
edit:
https://pastebin.com/5t58nQ1K another server crash that mentions flan
edit:
https://pastebin.com/0Sweywx7 also recreated with Pebble's shop (was given a test version from Pebble's and it works)
edit:https://pastebin.com/ZiBZtb1Z single player crash, not just a server based issue when using carpets

**Comment by Flemmli97** [comment]
update amendments as irrc they fixed this already.
