### ISSUE TITLE
[Feature Request] Multiple groups per player

### ISSUE THREAD

**Issue by johng3587** [Flemmli97/Flan#32]
It would be good to let a player join multiple groups, because i cant add people to another land area if they are already in a group. Could tags be used for this?

**Comment by Phr3d13** [comment]
it works for me with the UI/menu "/flan menu", if you mean you have two separate claim areas, and are trying to add one person to a group in each separate claim area.

**Comment by johng3587** [comment]
> it works for me with the UI/menu "/flan menu", if you mean you have two separate claim areas, and are trying to add one person to a group in each separate claim area.

Yes, lets say i own 2 land plots. I want to add someone to a group in plot A so they can build, and i want to add the same person to a group in plot B, but when i try to add user to plot B, it says they are already in a group.

**Comment by Phr3d13** [comment]
Yes, that works fine for me when using "/flan menu"

**Comment by johng3587** [comment]
Strange, it doesn't seem to work here. Ill do some more testing.
