### ISSUE TITLE
[Feature Request]: Add toggleable protection for 1) hostile mobs and 2) nametagged entitys

### ISSUE THREAD

**Issue by Ferbook3000** [Flemmli97/Flan#321]
### Suggestions

Sometimes players don't want to share mob farms with other users or want something in exchange. Therefore, having a toggleable protections for hostile mobs would be useful.

On the other hand, very often players have pets in form of either passive, neutral or hostile mobs. Since a player might want to allow other players to kill hostile mobs, kill pigs for food or make angry some zombie piglins while keeping their pets safe from any damage, I think adding toggleable protection for nametagged mobs could be a good workaround.

**Comment by Flemmli97** [comment]
hostile permission wont be added. otherwise players cannot do anything if they are attacked in that claim.
but nametag can be considered
