### ISSUE TITLE
adminMode命令消失

### ISSUE THREAD

**Issue by zhentou2008** [Flemmli97/Flan#326]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

0.92.2

### Mod version

1.10.8

### Description

adminMode命令消失，op无法进入管理员模式
![屏幕截图 2024-08-23 220908](https://github.com/user-attachments/assets/00787638-5223-452d-92b8-2ee11a6b2491)

### Steps to reproduce

1. Step one

### Logs

adminMode命令消失，op无法进入管理员模式

**Comment by Flemmli97** [comment]
command has been renamed to bypass
