### ISSUE TITLE
Caused by: java.io.EOFException: End of input at line 165 column 31 path $[1].PermGroup.Co-Owner.flan:enderchest

### ISSUE THREAD

**Issue by MrZephyrGH** [Flemmli97/Flan#328]
### Modloader

Fabric

### Minecraft version

1.20.6

### Modloader version

0.15.11

### Mod version

flan-1.20.6-1.10.5-fabric

### Description

After my server crashed do to an unrelated issue because I was messing around, the server couldn't start back up and I was continuously getting this same error and have absolutely no idea how to fix it or what even caused it.

![image](https://github.com/user-attachments/assets/2862fa0a-d3a0-4ac3-94cc-2c4c50d5b19c)

### Steps to reproduce

(Not sure how this would be reproducible)

1. Crash server?
2. Start server back up
3. Issue occur

(Around 13 players on the server, nothing wrong with computer/server spec's)

### Logs

[crash-2024-08-30_10.51.53-server.txt](https://github.com/user-attachments/files/16816107/crash-2024-08-30_10.51.53-server.txt)

**Comment by Flemmli97** [comment]
your claims are corrupted. they should be under data/claimData ? in your world folder. and you would need to check the files there

**Comment by Flemmli97** [comment]
closing this since this should be resolved by now
