### ISSUE TITLE
Inventory "broken" after using "/flan menu"

### ISSUE THREAD

**Issue by Phr3d13** [Flemmli97/Flan#33]
#### Issue (The better the description the better i can solve the issue):
After using "/flan menu", I have to disconnect from the server and re-connect, because if I don't inventory becomes glitched(?) and item locations feel like they don't get updated or something. 

#### Steps to reproduce:
Log into server
use "/flan menu"
go back into your inventory
move some stuff around
put a block from your inventory into your hotbar
try to place that block

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.4
- Fabric: 0.11.1
- Flan: 1.2.2

**Comment by srnyx** [comment]
> #### Issue (The better the description the better i can solve the issue):
> After using "/flan menu", I have to disconnect from the server and re-connect, because if I don't inventory becomes glitched(?) and item locations feel like they don't get updated or something.
> 
> #### Steps to reproduce:
> Log into server
> use "/flan menu"
> go back into your inventory
> move some stuff around
> put a block from your inventory into your hotbar
> try to place that block
> 
> #### Affected Versions (Latest is NOT a version):
> * Minecraft: 1.16.4
> * Fabric: 0.11.1
> * Flan: 1.2.2
> 
> #### Other Mods (If you think it might be cause of an incompability):
> #### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE):

Wait, that's what's causing that bug? I've been so confused about why it's been happening on my server.

**Comment by Strike5223** [comment]
Happening with mine aswell!
