### ISSUE TITLE
Crash on fabric server 1.20.1 "NoClassDefFoundError: io/github/flemmli97/flan/api/permission/BuiltinPermission"

### ISSUE THREAD

**Issue by p0nx77** [Flemmli97/Flan#330]
### Modloader

Fabric

### Minecraft version

1.20.1

### Modloader version

Fabric 0.16.3

### Mod version

Flan 1.20.1-1.8.11

### Description

Crashlog:

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2024-09-11 19:30:00
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: io/github/flemmli97/flan/api/permission/BuiltinPermission
	at net.mehvahdjukaar.amendments.integration.FlanCompat.canPlace(FlanCompat.java:35)
	at net.mehvahdjukaar.amendments.events.behaviors.InteractEvents.onItemUsedOnBlock(InteractEvents.java:136)
	at net.mehvahdjukaar.amendments.events.ModEvents.onRightClickBlock(ModEvents.java:33)
	at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41)
	at net.minecraft.class_3225.handler$bnm000$fabric-events-interaction-v0$interactBlock(class_3225.java:1587)
	at net.minecraft.class_3225.method_14262(class_3225.java)
	at net.minecraft.class_3244.method_12046(class_3244.java:1140)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:10818)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: io.github.flemmli97.flan.api.permission.BuiltinPermission
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (aarch64) version 5.15.0-1049-oracle
	Java Version: 17.0.12, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 4018046464 bytes (3831 MiB) / 10334765056 bytes (9856 MiB) up to 19327352832 bytes (18432 MiB)
	CPUs: 4
	Processor Vendor: aarch64
	Processor Name: 
	Identifier: aarch64 Family 8 Model 0xd0c Stepping r0x3p1
	Microarchitecture: unknown
	Frequency (GHz): 2.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Virtio GPU
	Graphics card #0 vendor: Red Hat, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: version: 01
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): -0.00
	Memory slot #0 type: RAM
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): -0.00
	Memory slot #1 type: RAM
	Virtual memory max (MB): 11993.94
	Virtual memory used (MB): 10973.65
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx18G
	Fabric Mods: 
		allarrowsinfinityfix: All Arrows Infinity Fix 1.4
		amendments: Amendments 1.20-1.2.11
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.20.1
		animated_guns: Simple Animated Guns 1.3
		another_furniture: Another Furniture 1.20.1-3.0.1
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		artifacts: Artifacts 9.5.13
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			expandability: ExpandAbility 9.0.4
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		asynclocator: Async Locator 1.3.0
		azure-paxels: Azure Paxels 1.0.9
		azurelib: AzureLib 2.0.20
		badpackets: Bad Packets 0.4.1
		bakery: [Let's Do] Bakery 1.1.13
		balm-fabric: Balm 7.2.1
		beacon-range-extender: beacon-range-extender 1.0.0
		beautify: Beautify 1.1.0+1.20
		betterchunkloading: Better chunk loading mod 1.20.1-3.3
		bettercombat: Better Combat 1.8.3+1.20.1
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
			org_reflections_reflections: reflections 0.10.2
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		blossom-back: BlossomBack 2.1.1+1.20
		blossom-lib: BlossomLib 2.5.4+1.20
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
		blossom-tpa: BlossomTpa 2.2.1+1.20
		bookshelf: Bookshelf 20.1.8
		bushierflowers: Bushier Flowers 0.0.3-1.20.1
		bwncr: Bad Wither No Cookie Reloaded 3.17.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.13
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.13
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.13
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.13
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.13
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.13
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.13
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.13
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.13
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.13
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.13
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.13
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.13
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.13
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.13
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.13
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.13
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.13
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.13
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.13
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		candlelight: [Let's Do] Candlelight 1.2.13
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carrier: Carrier 1.12.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
		carryon: Carry On 2.1.2.7
		chefsdelight: Chefs Delight 1.0.3-fabric-1.20.1
		chimes: Chimes 2.0.1
		chunkloaders: Chunk Loaders 1.2.8+a
		chunky: Chunky 1.3.138
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clutter: Clutter 1.20-0.5.7
		collective: Collective 7.30
		coroutil: CoroUtil 1.20.1-1.3.5
		cozy: Cozy 1.1.1
		craftingpad: Crafting Pad 1.0.12
		create: Create 0.5.1-f-build.1335+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.0+1.20.1
			porting_lib_base: Porting Lib Base 2.3.0+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.0+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.0+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.0+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.0+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.0+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.0+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.0+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.0+1.20.1
				porting_lib_common: Porting Lib Common 2.3.0+1.20.1
			porting_lib_models: Porting Lib Models 2.3.0+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.0+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.0+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_core: Porting Lib Core 2.3.0+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.0+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.0+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		creativecore: CreativeCore 2.11.15
			net_minecraftforge_eventbus: eventbus 6.0.3
		cupboard: cupboard 1.20.1-2.2
		customvillagertrades: Custom Villager Trades 20.24.0
		diagonalfences: Diagonal Fences 8.1.3
			diagonalblocks: Diagonal Blocks 8.0.2
		doapi: [Let's Do] API 1.2.15
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		dummmmmmy: MmmMmmMmmMmm 1.20-1.8.14
		easyanvils: Easy Anvils 8.0.1
		elytraslot: Elytra Slot 6.3.0+1.20.1
		emojiful: Emojiful 4.2.0
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.15
			midnightlib: MidnightLib 1.1.0
		endrem: End Remastered 5.2.4
		explorerscompass: Explorer's Compass 1.20.1-2.2.3-fabric
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-hammers: Fabric Hammers 1.2.1
		fabric-language-kotlin: Fabric Language Kotlin 1.9.6+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.16.3
			mixinextras: MixinExtras 0.4.1
		fallingtree: FallingTree 4.3.4
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		fastasyncworldsave: fastasyncworldsave Mod 1.20.1-1.4
		ferritecore: FerriteCore 6.0.1
		filtpick: FiltPick 1.2.3
			libgui: LibGui 8.1.1+1.20.1
				jankson: Jankson 6.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		flan: Flan 1.20.1-1.8.11
			rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		geckolib: GeckoLib 4 4.4.2
			com_eliotlash_mclib_mclib: mclib 20
		getittogetherdrops: Get It Together, Drops! fabric-1.20-1.3.1
		hamsters: Hamsters 1.0.2-fabric
		handcrafted: Handcrafted 3.0.5
		healingcampfire: Healing Campfire 5.3
		iceberg: Iceberg 1.1.18
		immersive_aircraft: Immersive Aircraft 1.0.1+1.20.1
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.2.1
		itemcollectors: Item Collectors 1.1.9
		jade: Jade 11.7.0
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.18
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		jumpoverfences: Jump Over Fences 1.3.1
		knavesneeds: Knaves' Needs 2.0.1+1.20.1
		lazydfu: LazyDFU 0.1.3
		letitrain: letitrain 2.1.0
		lithium: Lithium 0.11.2
		luphieclutteredmod: Cluttered 2.1.0+1.20.1
		magnumtorch: Magnum Torch 8.0.2
		maxenchantx: Max Enchant X 1.3-1.20
		mc2discord: Mc2Discord 4.2.4
		mcwdoors: Macaw's Doors 1.1.0
		mcwfences: Macaw's Fences and Walls 1.1.0
		mcwpaintings: Macaw's Paintings 1.0.5
		mcwroofs: Macaw's Roofs 2.2.4
		mcwwindows: Macaw's Windows 2.2.1
		mine-spawners: mine-spawners 1.0
		minecraft: Minecraft 1.20.1
		moonlight: Moonlight 1.20-2.12.17
		movingelevators: Moving Elevators 1.4.5
		mr_no_moreaxolotldespawns: No More Axolotl Despawns! 1.0
		mru: Mineblock's Repeated Utilities 0.4.0+1.20
		naturalist: Naturalist 4.0.3
		natures_spirit: Nature's Spirit 1.6.3-1.20.1
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		nightlights: Night Lights 1.1
		offlineskins: OfflineSkins 1.20.1-v1a-fabric
		owo: oωo 0.11.2+1.20
		paraglider: Paragliders 20.1.3
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		pickablevillagers: Pickable Villagers 1.4.5+1.20.1
		player-animator: Player Animator 1.0.2-rc1+1.20
		polymorph: Polymorph 0.49.1+1.20.1
			spectrelib: SpectreLib 0.13.14+1.20.1
		puzzleslib: Puzzles Lib 8.1.15
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		reinfbarrel: Reinforced Barrels 2.4.1+1.20
			reinfcore: Reinforced Core 3.1.2+1.20
		resourcefullib: Resourceful Lib 2.1.20
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		right-click-harvest: Right-Click-Harvest 1.2.0
		roughlyenoughitems: Roughly Enough Items 12.0.697
			error_notifier: Error Notifier 1.0.9
		roughlyenoughresources: Roughly Enough Resources 2.9.0
		scarecrowsterritory: Scarecrows' Territory 1.1.11
		simplemagnets: Simple Magnets 1.1.10
		simplyswords: Simply Swords 1.56.0-1.20.1
		smarterfarmers: Smarter Farmers 1.20-1.8.0
		sophisticatedbackpacks: Sophisticated Backpacks 3.19.4+mc1.20.1-build.39
			porting_lib_loot: Porting Lib Loot 2.3.0+1.20.1
			porting_lib_model_loader: Porting Lib Model Loader 2.3.0+1.20.1
			team_reborn_energy: Energy 3.0.0
		sophisticatedcore: Sophisticated Core 0.5.108+mc1.20.1-build.39
			porting_lib_fluids: Porting Lib Fluids 2.3.0+1.20.1
		structory: Structory 1.3.4
		structory_towers: Structory: Towers 1.0.6
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		supplementaries: Supplementaries 1.20-2.8.4
			mixinsquared: MixinSquared 0.1.1
		terrablender: TerraBlender 3.0.1.7
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		things: Things 0.3.3+1.20
			lavender: Lavender 0.1.0-pre.18+1.20
				lavender-md: lavender-md 0.1.0-pre.3+1.20
				lavender-md-owo-ui: lavender-md-owo-ui 0.1.0-pre.3+1.20
		toms_storage: Tom's Simple Storage Mod 1.6.6
		toofast: TooFast 1.2.0
		trade_cycling: Trade Cycling 1.20.1-1.0.7
		tradingpost: Trading Post 8.0.2
		trampledisablerfabric: Trample Disabler 1.0.8
		trashcans: Trash Cans 1.0.18
		trashslot: TrashSlot 15.1.0
		trinkets: Trinkets 3.7.1
		universal-graves: Universal Graves 3.0.1+1.20.1
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.3+1.20.1
			polymer-core: Polymer (Core) 0.5.19+1.20.1
				polymer-networking: Polymer (Networking) 0.5.19+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.19+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.19+1.20.1
				polymer-common: Polymer (Common) 0.5.19+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.19+1.20.1
			predicate-api: Predicate API 0.2.1+1.20.1
			sgui: sgui 1.2.2+1.20
		universalenchants: Universal Enchants 8.0.0
			extensibleenums: Extensible Enums 7.0.1
		variantfurnaces: Variant Furnaces 1.2.0
		vinery: [Let's Do] Vinery 1.4.26
		visualworkbench: Visual Workbench 8.0.0
		watut: What Are They Up To 1.20.1-1.0.12
		waystones: Waystones 14.1.5
		xtraarrows: Xtra Arrows 3 3.0.4
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
			org_javassist_javassist: javassist 3.29.2-GA
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
	Server Running: true
	Player Count: 1 / 100; [class_3222['Ekk0x'/27165, l='ServerLevel[world]', x=-359.23, y=78.05, z=3662.70]]
	Data Packs: vanilla, Supplementaries Generated Pack, fabric, natures_spirit:modified_badlands, natures_spirit:modified_birch_forest, natures_spirit:modified_dark_forest, natures_spirit:modified_desert, natures_spirit:modified_flower_forest, natures_spirit:modified_jungle, natures_spirit:modified_mountain_biomes, natures_spirit:modified_savannas, natures_spirit:modified_swamp, natures_spirit:modified_windswept_hills
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

- Should I update to the latest version of FLAN to fix this? I am already using the latest version of the mod "Amendments" as well.

Thanks.

### Steps to reproduce

I really dont know the server just crashed out of nowhere. 

### Mods that might affect the issue

amendments-1.20-1.2.11-fabric.jar

### Logs

https://paste.gg/p/anonymous/849c84abf85b4b308d3e25923c4502cd

**Comment by p0nx77** [comment]
update: I just updated to the latest FLAN version, but the issue keeps happening.

**Comment by Flemmli97** [comment]
update amendments

**Comment by p0nx77** [comment]
> update amendments

Hello, Amendments is already on the latest version, and the server still crashes. I have removed FLAN from my server and its running with no crashes. the only problem is when both mods are running together. any suggestions?
