### ISSUE TITLE
Flan crashes server when trying to use in game items as buy/sell for claim blocks

### ISSUE THREAD

**Issue by payphone101** [Flemmli97/Flan#331]
### Modloader

Fabric

### Minecraft version

1.21.1

### Modloader version

Fabric 0.16.3

### Mod version

Flan 1.21.1-1.10.8

### Description

Server crashing when trying to use items to buy/sell claim blocks

### Steps to reproduce

1. Install Flan
2. Configure to use "minecraft:diamond" to be used as buy/sell items
(refer to configs that [use single item formatting](https://mclo.gs/nxiNrcK) or [use multiple item format but only specify one item](https://mclo.gs/BR1vHOm)
3. start server

### Logs

1. https://mclo.gs/QgkfCty
2. https://mclo.gs/pWUv0p9

**Comment by Dormdude** [comment]
I'm having the same exact issue. I've tried about a dozen different ways of typing it and every single time it crashes. The default config doesn't resemble the example which just adds to the confusion for me.

**Comment by Flemmli97** [comment]
selling only allows one item atm. so correct way would be:
```json
"sellIngredient":{
     "item": "minecraft:diamond"
 }
```
