### ISSUE TITLE
[Feature] Add private sign claiming

### ISSUE THREAD

**Issue by N0tHorizon** [Flemmli97/Flan#333]
### Suggestion

Chest, barrel, and shulker claiming with a sign even when there isn't a claim over the storage block. Like if you right click without crouching or write [private] or [secured]. Putting this on the storage block should automatically add your name to it so you can access it. If you right click the sign without crouching, you can edit the sign and add other people's names to give access to the storage block. There are plugins for this, but it would be nice to have it in one single mod plus this would make one of the first fabric mod versions of this idea. Maybe add a config option for this to disable/enable it incase ppl have other mods for this.

**Comment by Flemmli97** [comment]
single block locking is out of scope for this mod. sorry

**Comment by N0tHorizon** [comment]
Okay
