### ISSUE TITLE
"Prevent hostile mob" ban the spawn of mobs in all the world

### ISSUE THREAD

**Issue by cutekitticat** [Flemmli97/Flan#336]
### Modloader

Forge

### Minecraft version

1.20.1

### Modloader version

forge 47.3.0

### Mod version

1.10.8

### Description

I recently created a server that needs a spawn without mobs and that prevent greiffing, so I had to modify the mob spawn in the config, unfortunately it blocked the spawn of almost every mobs, it’s been 2 months since my server is open with practically no mobs 

### Steps to reproduce

Go to config/flan/flan_config.json 
modify "flan:mob_spawn": "ALLFALSE" to "flan:mob_spawn": "ALLTRUE"

### Logs

![image](https://github.com/user-attachments/assets/9cf2887e-7359-4ec6-a494-540c5147eaeb)

**Comment by Flemmli97** [comment]
yes that is how it works. config applies globally. 
if you only want it for claims then toggle it in the claim (admin claims ignore allfalse and alltrue)

**Comment by cutekitticat** [comment]
It’s strange because I changed a lot of parameters but they only works in the claim
