### ISSUE TITLE
Crash when hitting another player with a Piercing Crossbow in a claim

### ISSUE THREAD

**Issue by kd8lvt** [Flemmli97/Flan#34]
#### Issue (The better the description the better i can solve the issue):
Shooting a spectral arrow at a player within a claim crashes the server. Normal arrows do not cause a crash.. 

#### Steps to reproduce:
(EDIT: Both normal and spectral arrows cause the issue, making me think it's piercing at this point)
Claim an area. the PvP setting doesn't affect the outcome.
Shoot another player that is standing within the claim, using an arrow - spectral or otherwise. Noticed with a Piercing 3 Crosswbow, untested otherwise.
The server should crash.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.5
- Fabric: 0.11.1
- Flan: 1.16.2-1.2.2

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE): 
[https://gist.github.com/kd8lvt/099c8cf208d79405064b06fa9b6e4c68](https://gist.github.com/kd8lvt/099c8cf208d79405064b06fa9b6e4c68)

**Comment by MorrisTYB** [comment]
I am getting the same error as well.

**Comment by MorrisTYB** [comment]
I have found a temporary solution for the time being, in your server's files navigate to /config/flan/flan_config.json, and paste the following in. 
```json
  "globalDefaultPerms": {
    "minecraft:overworld": {
      "HURTPLAYER": true
    },
    "minecraft:the_nether": {
      "HURTPLAYER": true
    },
    "minecraft:the_end": {
      "HURTPLAYER": true
    }
  },
```
Please note that the file already contains a `"globalDefaultPerms" : {}` Just be weary of that when copying and pasting. 

This will prevent players from being able to disable PVP in their land claims, and therefore avoid the crash.
