### ISSUE TITLE
Arrows crash the game

### ISSUE THREAD

**Issue by steelsicarius** [Flemmli97/Flan#340]
### Modloader

Forge

### Minecraft version

1.21.1

### Modloader version

neoforge 21.1.72

### Mod version

1.10.8

### Description

Shooting an arrow crashes the game (whether with a bow or any other tool).

### Steps to reproduce

1. Enter the world
2. you shoot an arrow
3. crash

### Mods that might affect the issue

Minecraft 1.21.1
Neoforge 21.1.72
Flan 1.10.8

### Logs

https://gist.github.com/steelsicarius/056b9b7b1fe549f871e4f4e5d87a7ada

**Comment by xHaMMaDy** [comment]
+1
