### ISSUE TITLE
Laggy players able to break into bases

### ISSUE THREAD

**Issue by srnyx** [Flemmli97/Flan#44]
#### Issue:
Players with high ping are able to break into bases. Flan doesn't replace broken blocks for them until a few seconds after.

#### Steps to reproduce:
1. Install mod
2. Make a claim and deny breaking permissions
3. Get a player with high ping (5k+) to try and break in

#### Affected Versions:
- Minecraft: 1.16.5
- Fabric: IDK, API is 0.32.0
- Flan: 1.2.2

**Comment by Binero** [comment]
Can they actually break blocks, or do they simply lag through walls?

**Comment by srnyx** [comment]
> Can they actually break blocks, or do they simply lag through walls?

They just lag through the wall
*By the way I shutdown my modded server so I can't really help with testing or anything*

**Comment by Flemmli97** [comment]
reopen if issue persist
