### ISSUE TITLE
crossbow crashes server

### ISSUE THREAD

**Issue by xXxIshadowxXX** [Flemmli97/Flan#45]
#### Issue (The better the description the better i can solve the issue):
when people shoot each other within claims on my server it crashes, however it never makes a crash report, and the logs abruptly stop and it begins saying the UUID of all players

#### Steps to reproduce:
- make a claim
- shoot someone with a crossbow

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.5
- Fabric: 0.11.1-1.16.5
- Flan: 1.16.2-1.2.2

**Comment by Flemmli97** [comment]
update the mod
