### ISSUE TITLE
[Issues] Eggs Use / Mobs Trample.

### ISSUE THREAD

**Issue by Strike5223** [Flemmli97/Flan#48]
Current Issues:

Players can lead mobs into a claim and get them to trample onto crops.
Players are able to spam place eggs in player claims (It tells player they cannot do this) however it still throws and spawns chicken.

I was wondering if it was possible to make it so mobs can't go into a claim at all.

**Comment by Strike5223** [comment]
Another suggestion would be to stop players from picking up and dropping items.

**Comment by Flemmli97** [comment]
please split the features and bugs into separate issues

**Comment by Flemmli97** [comment]
eggs fixed. but i see no reason to do expensive collision checks to prevent mobs entering claims when a simple fence wall is enough

**Comment by Strike5223** [comment]
Thanks for working on issues so fast and I have moved the features to their own.
