### ISSUE TITLE
Works with no other mod

### ISSUE THREAD

**Issue by NiaTale** [Flemmli97/Flan#50]
So originally whenever i used it alone is was fine, but anytime i added ANY mod it starts going minimum claim block 100, then when i expand the area it goes not enough claim block. even if its just 100 blocks, but now its doing it even when its only the flan mod and fabric api in the mod folder.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.5
- Fabric: 1.16
- Flan: 1.16.2-1.2.6

#### Other Mods (If you think it might be cause of an incompability):
so ive tried adding these all one by one but everyone does the same error for me.
all the origin mods require origin but the origin mod dosent work even by itself,
Adorn.
bettersleeping.
clothes=config
deuf
extra keybind.
extra origin.
image2map
medival weapons.
moborigins.
optifabric
origin
origin classes.
pekhui.
repurposed structures.
roughly enough items.
secret rooms.
slime origin.
taterzen.
wraith waystones.
xaeros minimap.

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE): 
im not sure how to show it

**Comment by Flemmli97** [comment]
fabric api version?

**Comment by NiaTale** [comment]
> fabric api version?

yes 1.16

**Comment by Flemmli97** [comment]
whats it saying if you pull out the hoe?

**Comment by NiaTale** [comment]
> whats it saying if you pull out the hoe?

it says nothing. but when i click it the blue part comes. click it again it says minimum claijmsize is 100. go out a hundred blocks and it says, not enough claim blocks.

**Comment by Flemmli97** [comment]
10x10=100

**Comment by NiaTale** [comment]
> 10x10=100

oh god I'm sorry. i didn't realize how fuzzy my brain is.
