### ISSUE TITLE
Cannot Disable Mob Spawn

### ISSUE THREAD

**Issue by 1231sadqwf** [Flemmli97/Flan#53]
#### Issue (The better the description the better i can solve the issue):
I cannot disable mob spawn in flan menu.

#### Steps to reproduce:
![image](https://user-images.githubusercontent.com/62546980/118402936-b43e4580-b69e-11eb-9b53-7cb0fa84f75b.png)

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.5
- Fabric(API): fabric-api-0.34.2+1.16
- Flan: flan-1.16.2-1.3.2

#### Other Mods (If you think it might be cause of an incompability. Adding a link + the used version will help greatly):
I remove all the installed mod and create a new world also cannot disable mob spawn

**Comment by Flemmli97** [comment]
yes cause its disabled by default. enable in config

**Comment by 1231sadqwf** [comment]
my config is enable
