### ISSUE TITLE
Buggy inventory when using /flan adminMode

### ISSUE THREAD

**Issue by srnyx** [Flemmli97/Flan#57]
#### Issue:

After using "/flan adminMode", I have to disconnect from the server and re-connect, because if I don't, my inventory becomes glitched and item locations feel like they don't get updated or something.
_I just copied this over from https://github.com/Flemmli97/Flan/issues/33 cause it's basically the same thing._

This may also happen with other Flan commands, not too sure.

#### Steps to reproduce:

1. Log into the server
2. Use "/flan adminMode"
3. Go back into your inventory
4. Move some stuff around
5. Put a block from your inventory into your Hotbar
6. Try to place that block

OR
1. Log into the server
2. Use "/flan adminMode"
3. Shift-click items into your inventory
4. The items will go to the 2nd row, skipping the 1st

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.5
- Fabric API: 0.34.6
- Flan: 1.3.3

#### Other Mods (If you think it might because of an incompatibility. Adding a link + the used version will help greatly):

https://www.curseforge.com/minecraft/modpacks/simpearth/files/3340757

**Comment by Flemmli97** [comment]
adminmode shouldnt cause that. and i am unable to reproduce it. does it happen with only flan installed?

**Comment by MaxBr5** [comment]
<pre>What other mods do you use?</pre>

**Comment by Flemmli97** [comment]
reopen if issue persist
