### ISSUE TITLE
[SUGGESTION] Kibe Angel Ring flight

### ISSUE THREAD

**Issue by srnyx** [Flemmli97/Flan#58]
Add some sort of config setting that makes it so people can only use the Angel Ring from [Kibe](https://www.curseforge.com/minecraft/mc-mods/kibe) in claimed areas.
This could also add a new permission called "Flight" or something that would disallow people without the permission from flying.

**Comment by Flemmli97** [comment]
actually i might have misinterpreted this. since i made it so flight is toggable in claims and not that flight outside claims is disallowed.
so you want flight outside claims to be off but inside claims to be on?
tbh i dont see the benefit of doing this

**Comment by srnyx** [comment]
> so you want flight outside claims to be off but inside claims to be on?

Yes

> tbh i dont see the benefit of doing this

It'd make it so people can only fly inside of their claimed areas. Instead of being able to creative-fly (fly using Angel Ring) around anywhere, they can only use it to like build or do stuff inside of their base.
It's currently extremely easy to do basically anything with the Angel Ring, but I don't want to to be that easy, but I still want people to be able to fly in areas they've claimed.
I'm bad at explaining things, but when my server used to run on Paper-Spigot, the claiming plugin I used has this feature and I loved it.
