### ISSUE TITLE
bug GUI

### ISSUE THREAD

**Issue by ghost** [Flemmli97/Flan#61]
https://www.youtube.com/watch?v=biiF2MRMQdA

flan: 1.17-1.4.2
server: 1.17 java: 1.16 api: 0.35.0+1.17

**Comment by Flemmli97** [comment]
show the lang config

**Comment by ghost** [comment]
https://pastebin.com/RTiZLvGT

**Comment by Flemmli97** [comment]
can you also post the logs?

**Comment by ghost** [comment]
no errors in logs

**Comment by ghost** [comment]
I think it's a bug on 1.17 api 0.35 check it out

**Comment by Flemmli97** [comment]
post the log anyway.

**Comment by Flemmli97** [comment]
since im not getting the bug

**Comment by ghost** [comment]
[latest(7).log](https://github.com/Flemmli97/Flan/files/6645402/latest.7.log)

**Comment by Flemmli97** [comment]
please use a paste for the log. also what happesn if you just have flan alone?

**Comment by ghost** [comment]
https://pastebin.com/MVhPwR4h

**Comment by ghost** [comment]
I will test a separate one in about an hour . then I will write

**Comment by ghost** [comment]
I found the problem... it was enough to remove the mod GOLFIV-0.3.2 and the menu works as it should... so the fault is the cooperation of the flan mod with golfiv

**Comment by ghost** [comment]
https://www.curseforge.com/minecraft/mc-mods/golfiv

**Comment by Flemmli97** [comment]
[removeCreativeNBTTags] this config yes
