### ISSUE TITLE
Mobs do not spawn in claimed areas, regardless of MOBSPAWN's value

### ISSUE THREAD

**Issue by Geometrically** [Flemmli97/Flan#62]
#### Issue (The better the description the better i can solve the issue):
Hostile mobs do not spawn in claimed areas.

#### Steps to reproduce:
Claim an area, wait till night 

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.17
- Fabric(API): 0.34.9+1.17
- Flan: 1.4.2

**Comment by wh0oo** [comment]
I kind of had this issue.  The solution, for me at least, was to remove the override inside the configuration file (it is one of the default 4).  It defaults then to allowing mobs to spawn, but allows players to toggle it.

The language for this setting is confusing, and the wiki  entry about it only helped me after I read it 20 times

Im using 1.5.0 though.
