### ISSUE TITLE
Way too many passive (water) mobs spawning in claims

### ISSUE THREAD

**Issue by Wesley1808** [Flemmli97/Flan#63]
#### Issue (The better the description the better i can solve the issue):
Passive water mob spawning in claims is much larger than areas outside of the claim. Almost all of the water mobs seem to spawn inside the claims. Even when there are no claims around, these mobs don't seem to spawn in oceans anymore at all until I make a claim there.

#### Steps to reproduce:
Head to an ocean biome and check for any mobspawns. Then claim an area inside the ocean and check for mob spawns again.
All of the mobs should spawn within the claim itself, and none or almost none outside of it.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.17
- Fabric(API): 0.34.8
- Flan: 1.5.0 1.17

**Comment by MaxBr5** [comment]
<pre>No one cares. Besides, fishies will not kill you.</pre>

**Comment by Shipool** [comment]
> No one cares. Besides, fishies will not kill you.

I care.
Passive Aquatics aren't spawning outside of claims, this is making oceans feel entirely dead.
Players on my server aren't too happy about it, but we also don't want to remove land management, so we're using workarounds of claiming ocean pieces until it's fixed.

**Comment by wh0oo** [comment]
I JUST had a player report this behavior.  I can confirm. And yes, we care.  Breeding axelotles requires fish.

**Comment by Flemmli97** [comment]
set ANIMALSPAWN in globalDefaultPerms to FALSE

**Comment by Wesley1808** [comment]
Thanks, we had already done that. But oceans and rivers still seem to remain completely devoid mobs.

**Comment by MaxBr5** [comment]
<pre>Now I care. I don't want dead oceans.</pre>
