### ISSUE TITLE
Glass gets stuck

### ISSUE THREAD

**Issue by Jan3004** [Flemmli97/Flan#65]
[https://youtu.be/YrmMnymWTa0](url)

I think the video describes the problem very good. I dont know if this is a Mod bug or something from Minecraft.

**Comment by Flemmli97** [comment]
that is just client side

**Comment by Jan3004** [comment]
so no fix for that?

**Comment by Flemmli97** [comment]
yesn't. i could prob send a blockupdate packet to every neighbor everytime a player tries placing something but that seems rather unnecessary for so few affected blocks and a clientside thing

**Comment by Jan3004** [comment]
ok thanks :) 
Idk if this is a problem from your mod, but in my entire world there wont spawn any mobs

**Comment by Flemmli97** [comment]
that is just fixed in new version
