### ISSUE TITLE
Crash on startup caused by fabric versions of flan trying to load 1.17 blocks in the supposed 1.16 version of the mod.

### ISSUE THREAD

**Issue by LordDecay26** [Flemmli97/Flan#68]
#### Issue (The better the description the better i can solve the issue):
1.16.5-1.5.0 & 1.16.5-1.5.1 versions of the mod try to load 1.17 minecraft resources, resulting in a crash on startup on servers. 

#### Steps to reproduce:

just download the mod onto a server and try loading it up

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.5
- Forge: N/A
- Fabric(API):  0.34.6+1.16
- Flan: 1.5.0 & 1.5.1

#### Other Mods (If you think it might be cause of an incompability. Adding a link + the used version will help greatly):

as shown in the crash log

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE):
crashlog:
https://pastebin.com/QyAAhFdb

lastest.log:
https://pastebin.com/xnsvCSC0

PLEASE HELP

**Comment by Flemmli97** [comment]
can you run the game with -Dmixin.debug.export=true and put the output here?
it should then be .mixin.out/net/minecraft/class_3218.class

**Comment by LordDecay26** [comment]
no i cant because i cant run the game, because it immediately crashes

**Comment by Flemmli97** [comment]
yes but it will still create the files

**Comment by Flemmli97** [comment]
reopen if issue persist
