### ISSUE TITLE
Total claim blocks less than used

### ISSUE THREAD

**Issue by frederic-orlando** [Flemmli97/Flan#7]
#### Issue:

i used to have around 1k claim and 0 bonus, and i claim my area which use almost all that claim blocks
after that i never check my /list anymore

when i tried to resize my claim (make it bigger), it said not enough claim blocks. so i check my /list and that happen
https://imgur.com/a/lcW8CIo (in game screenshot)

#### Affected Versions:

- Minecraft: 1.16.2
- Fabric: 0.9.3 build 207
- Flan: 1.0.6

**Comment by Flemmli97** [comment]
can you post the logs at that time? (using pastebin or something)

**Comment by frederic-orlando** [comment]
todays log
https://pastebin.com/kV4gfqz4

latest log
https://pastebin.com/ieeJ27QY

i can't pinpoint when the issues happen, but i realize it after using /flan list command around 01:14

https://imgur.com/a/HikQ9pR (flan list result)

**Comment by Flemmli97** [comment]
hmm i cant find anything in the logs. since the used claim check calculates the actual used claim blocks everytime from scratch the only explanation would be either ur player file failed to save which the log doesnt seem to indicate or the file got changed/deleted

**Comment by frederic-orlando** [comment]
i think the problem are not used ones.

i have my starting blocks set to 500 and ticksForNextBlock set to 800

everytime the issue occurs, it resets the claim blocks to starting (500)
so i think the issues happen around 4 hours before i ran the command

**Comment by Flemmli97** [comment]
so... why is the server in offline mode? cause that is with a high chance the reason for this

**Comment by Flemmli97** [comment]
closed unless you show that you own the game and it still happens then
