### ISSUE TITLE
[1.17] Players with no permissions can interact with the Dragon Egg inside a claim and teleport it away.

### ISSUE THREAD

**Issue by Gbergz** [Flemmli97/Flan#71]
#### Issue
Title^ But, (Players with no permissions can interact with the Dragon Egg inside a claim and teleport it away.)

#### Steps to reproduce:
1. Claim an area
2. Let someone who has no permissions interact with dragon egg.
3. Dragon egg teleports away.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.17
- Fabric: Yes, Fabric.
- Fabric API: fabric-api-0.36.0+1.17.jar
- Flan: flan-1.17-1.5.1.jar

#### Other Mods:
No other mods.

**Comment by Flemmli97** [comment]
update

**Comment by Gbergz** [comment]
Works now, can't move it. Thanks!
