### ISSUE TITLE
Claims Are Useless Due To Sticks, And Golden Hoes

### ISSUE THREAD

**Issue by Atchbo2001** [Flemmli97/Flan#73]
#### Issue (The better the description the better i can solve the issue):
Any player can interact with Chests, Doors, Trapped Doors, Basically anything with the single click of a golden hoe and or stick!

#### Steps to reproduce:
Take a stick or a golden hoe and right click to interact with the object in a claim

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.17
- Fabric(API): 0.34.8
- Flan: 1.5.2

**Comment by Flemmli97** [comment]
duplicate #70
