### ISSUE TITLE
list admin claims returns an error

### ISSUE THREAD

**Issue by wh0oo** [Flemmli97/Flan#77]
#### Issue (The better the description the better i can solve the issue):

![2021-07-13_09 20 02](https://user-images.githubusercontent.com/45668419/125469251-f67ed40a-f016-4d0d-9cae-140ba7df6238.png)

#### Steps to reproduce:
Do /flan listAdminClaims as an admin

#### Affected Versions (Latest is NOT a version):

- Minecraft:   1.17.1
- Fabric(API):   0.37.0+1.17
- Flan:   1.17.1-1.5.4

**Comment by Flemmli97** [comment]
read the changelog
