### ISSUE TITLE
16.1

### ISSUE THREAD

**Issue by sakiraa** [Flemmli97/Flan#8]
Not an issue really, do you maybe have a 1.16.1 version archived somewhere? And if not, could you allow me to make a PR for it? 
You're free to publish it without credit, I just can't update my server because *biomes are very broken in .2~*

**Comment by Flemmli97** [comment]
you are free to port and pr it. (gotta work on a license in near future)

**Comment by Flemmli97** [comment]
since there hasnt been anything here for quite a while i guess the releases work in all 1.16 version. if issue arise using version below 1.16.2 create a new issue again
