### ISSUE TITLE
Others can not use "Gunpowder Signshop" in the claim

### ISSUE THREAD

**Issue by JackMeds** [Flemmli97/Flan#80]
#### Issue (The better the description the better i can solve the issue):

Others can not use "Gunpowder Signshop" in the claim

https://www.curseforge.com/minecraft/mc-mods/gunpowder-signshop

Right click the sign no response

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.17.7
- Fabric(API): 0.11.6
- Flan:1.6.0

#### Other Mods (If you think it might be cause of an incompability. Adding a link + the used version will help greatly):

Gunpowder Signshop
https://www.curseforge.com/minecraft/mc-mods/gunpowder-signshop

**Comment by Flemmli97** [comment]
prob need to adjust blockEntityTagIgnore in the config

**Comment by Flemmli97** [comment]
change the tag from gunpowder.owner to gunpowder:owner or gprops
