### ISSUE TITLE
Cannot launch with flan installed anymore.

### ISSUE THREAD

**Issue by AchalS-iglu** [Flemmli97/Flan#81]
#### Issue (The better the description the better i can solve the issue):

So after a recent fuckup I think I upgraded my world to 1.17.1 and restoring backup to get it back to 1,17. I cannot boot my world with flan installed anymore, I do not know why or how but I would like to delete all flan data to hopefully get it running again. How would I do that?

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.17
- Forge: NA
- Fabric(API): 0.36.0
- Flan: 1.5.5

#### Other Mods (If you think it might be cause of an incompability. Adding a link + the used version will help greatly):
https://pastebin.com/V7r0YE8U

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE):
https://pastebin.com/LCJt2Je7

**Comment by AchalS-iglu** [comment]
Fixed for now by setting inactivity days to -1

**Comment by Flemmli97** [comment]
one (or more) of ur playerdata json is broken. you would need to find the broken one and fix it (or delete it)
the data are stored in ./playerdata/claimData.
future version ignore broken files and treat them with default values
