### ISSUE TITLE
[Feature Request] mod compat Money and Sign Shops

### ISSUE THREAD

**Issue by Caltinor** [Flemmli97/Flan#82]
#### Feature Request:
I would like to request compat for one of my mods.  I created the mod Money Mod and Sign Shops [CF Page](https://www.curseforge.com/minecraft/mc-mods/dicemc-money-mod).  Like flan, this mod works entirely serverside, so it fits well in the server-only ecosystem.  I have a few modpack authors that have requested this feature, so integration would be greatly appreciated.  This mod is only on forge though, so if not being on fabric causes any issues with willingness to build in compat, please let me know.

[GitHub Repo](https://github.com/Caltinor/DiceMC-Money-Mod/tree/1.16)
#### Aids for implementation:
Charging players involves calling `MoneyManager.INSTANCE.ChangeBalance(new ResourceLocation("dicemcmm", "player"), playerUUID, -amount)`  negative values remove money from the player.  positive values add.

**Comment by Flemmli97** [comment]
using ur api calls errors cause ur not setting the world and as such its null. 
so instead im using the implementation calls atm

**Comment by Caltinor** [comment]
I see the flaw now.  Thank you for both pointing that out and for implementing this into Flan.
