### ISSUE TITLE
Bewitchment cauldrons

### ISSUE THREAD

**Issue by VoidLock92** [Flemmli97/Flan#84]
Here is what the bewitchment devs said. I am trying to get support for their cauldrons in flan.
https://github.com/MoriyaShiine/bewitchment/issues/164

**Comment by Flemmli97** [comment]
hmm i cant comment on that issue so im gonna do it here:
what is the maven error? it works on my end

as for the compat then:
on their end they can just use ObjectToPermissionMap#registerBlockPredicateMap to assign a block to a permission

**Comment by Flemmli97** [comment]
reposting cause i accidentally deleted it:

what is the maven error?
+
use ObjectToPermissionMap#registerBlockPredicateMap to assign blocks to a permission

**Comment by MoriyaShiine** [comment]
Hi! I'm the owner of Bewitchment, here's the error I got:

`
A problem occurred configuring root project 'bewitchment'.
> Could not resolve all files for configuration ':modCompileClasspath'.
   > Could not find io.github.flemmli97:flan:1.6.0-1.17.1.
     Searched in the following locations:
       - file:/home/moriya/IdeaProjects/bewitchment/build/loom-cache/flan-1.6.0-1.17.1-fabric-api.jar
       - file:/home/moriya/IdeaProjects/bewitchment/build/loom-cache/flan-fabric-api.jar
       - file:/home/moriya/IdeaProjects/bewitchment/.gradle/loom-cache/remapped_mods/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
       - https://maven.fabricmc.net/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
       - https://libraries.minecraft.net/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
       - https://repo.maven.apache.org/maven2/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
       - file:/home/moriya/.gradle/caches/fabric-loom/1.6.0-1.17.1/flan-1.6.0-1.17.1-fabric-api.jar
       - file:/home/moriya/IdeaProjects/bewitchment/.gradle/loom-cache/1.6.0-1.17.1/flan-1.6.0-1.17.1-fabric-api.jar
       - https://maven.terraformersmc.com/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
       - https://maven.shedaniel.me/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
       - https://maven.theillusivec4.top/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
       - https://oss.sonatype.org/content/repositories/snapshots/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
       - https://maven.blamejared.com/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
       - https://api.modrinth.com/maven/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
       - https://maven.ryanliptak.com/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
       - https://gitlab.com/api/v4/projects/21830712/packages/maven/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
       - https://jitpack.io/io/github/flemmli97/flan/1.6.0-1.17.1/flan-1.6.0-1.17.1.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

`

I'm not sure what the version is supposed to be so I took the latest from curseforge and that didn't work, so I opened the maven in a browser to see what versions are actually on it and it just says it's an invalid package id (https://gitlab.com/api/v4/projects/21830712/packages/maven)

**Comment by Flemmli97** [comment]
oops... the docs are wrong. my bad. switch mc version and modversion so its 1.17.1-1.6.0
derp

**Comment by MoriyaShiine** [comment]
I see, thanks lol, but now it's having an issue finding gunpowder

`Could not GET 'https://jitpack.io/io/github/gunpowder/gunpowder-currency/1.0.6+gunpowder.1.0.6.mc.1.17/gunpowder-currency-1.0.6+gunpowder.1.0.6.mc.1.17.pom'. Received status code 400 from server: Bad Request`

**Comment by Flemmli97** [comment]
disable transitive dependencies. you dont need gunpowder since its an optional dependency

**Comment by MoriyaShiine** [comment]
They are disabled

**Comment by MoriyaShiine** [comment]
Never mind only 2/3 of the were lol

**Comment by MoriyaShiine** [comment]
Aaaand disabling transitive gives me this

`A problem occurred configuring root project 'bewitchment'.
> Could not resolve all files for configuration ':modCompileClasspath'.
   > Could not find flan-1.17.1-1.6.0-fabric-api.jar (io.github.flemmli97:flan:1.17.1-1.6.0).
     Searched in the following locations:
         https://gitlab.com/api/v4/projects/21830712/packages/maven/io/github/flemmli97/flan/1.17.1-1.6.0/flan-1.17.1-1.6.0-fabric-api.jar
   > Could not find flan-1.17.1-1.6.0-fabric.jar (io.github.flemmli97:flan:1.17.1-1.6.0).
     Searched in the following locations:
         https://gitlab.com/api/v4/projects/21830712/packages/maven/io/github/flemmli97/flan/1.17.1-1.6.0/flan-1.17.1-1.6.0-fabric.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html`

**Comment by Flemmli97** [comment]
remove the modloader part. since 1.17 only has a fabric version
so io.github.flemmli97:flan:1.17.1-1.6.0:api
its a bit misleading. the README for the 1.16 branch and 1.17 is a bit different

**Comment by MoriyaShiine** [comment]
Everything works now, thanks haha
