### ISSUE TITLE
Lag caused by flan checking getClaimAt() in ClaimStorage

### ISSUE THREAD

**Issue by Wesley1808** [Flemmli97/Flan#87]
#### Issue (The better the description the better i can solve the issue):
Large lagspikes caused by slow getClaimAt() checks in ClaimStorage.
This is very noticeable when firing a lot of pistons or having flowing water, like flush style mobfarms.

#### Steps to reproduce:
Have large contraptions with lots of pistons fire at the same time. TPS will drop a lot.

![Schermopname (11)](https://user-images.githubusercontent.com/74668381/128629714-74138ce9-48ba-4e98-9853-f8c03929c1d8.png)

Using Spark I have checked this out a bit and it seems the main problem is that for all checks that require to get the claim location `ClaimStorage.getClaimAt()` it uses `Long2ObjectArrayMap`, which seems unnecessary as Flan doesn't store any arrays in it. I have tested it using another implementation that is much faster, for example `Long2ObjectOpenHashMap`, which still seems to work just fine. Is there any reason for Flan to use `Long2ObjectArrayMap` that I haven't noticed?

![graphs-11](https://user-images.githubusercontent.com/74668381/128629739-c475fda3-b48d-4b32-b067-f0c4b4851ef5.png)
Source: https://github.com/austinv11/Long-Map-Benchmarks

The other thing you can easily optimize is by removing `this.claims.containsKey()` and replacing it with a null check after using `this.claims.get()`.

get() and containsKey() essentially do the exact same thing,  except one returns a boolean if it exists, and the other returns the value.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.17.1
- Fabric(API): 0.37.1
- Flan: 1.5.3 - 1.17 (But in the newest commits this code is no different).

**Comment by Flemmli97** [comment]
idk why i used Long2ObjectArrayMap. gonna change it
