### ISSUE TITLE
[Crash] When adding Potion effect via menu it crashes the server.

### ISSUE THREAD

**Issue by ThebigTijn** [Flemmli97/Flan#96]
When a player open the menu with or without permission. and tries to add a potion via the anvil menu. it will crash the server for "Ticking Entity" and i got reports from players even getting chunk banned after testing it.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/1/21 7:53 AM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.class_3222.method_26082(Lnet/minecraft/class_1293;)V
	at io.github.flemmli97.flan.claim.Claim.lambda$applyEffects$11(Claim.java:512)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.github.flemmli97.flan.claim.Claim.applyEffects(Claim.java:512)
	at io.github.flemmli97.flan.event.EntityInteractEvents.updateClaim(EntityInteractEvents.java:334)
	at io.github.flemmli97.flan.player.PlayerClaimData.tick(PlayerClaimData.java:257)
	at net.minecraft.class_3222.handler$zeg000$tickData(class_3222.java:2641)
	at net.minecraft.class_3222.method_5773(class_3222.java)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.handler$bih000$modifiedRunLoop(MinecraftServer.java:6810)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.flemmli97.flan.claim.Claim.lambda$applyEffects$11(Claim.java:512)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.github.flemmli97.flan.claim.Claim.applyEffects(Claim.java:512)
	at io.github.flemmli97.flan.event.EntityInteractEvents.updateClaim(EntityInteractEvents.java:334)
	at io.github.flemmli97.flan.player.PlayerClaimData.tick(PlayerClaimData.java:257)
	at net.minecraft.class_3222.handler$zeg000$tickData(class_3222.java:2641)
	at net.minecraft.class_3222.method_5773(class_3222.java)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 150
	Entity Name: TGrag
	Entity's Exact location: 68889.40, 63.00, 41958.51
	Entity's Block location: World: (68889,63,41958), Chunk: (at 9,3,6 in 4305,2622; contains blocks 68880,0,41952 to 68895,255,41967), Region: (134,81; contains chunks 4288,2592 to 4319,2623, blocks 68608,0,41472 to 69119,255,41983)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

-- Affected level --
Details:
	All players: 2 total; [class_3222['W1nterSeal'/42, l='ServerLevel[world]', x=-546.18, y=73.00, z=-445.39], class_3222['TGrag'/150, l='ServerLevel[world]', x=68889.40, y=63.00, z=41958.51]]
	Chunk stats: ServerChunkCache: 4203
	Level dimension: minecraft:overworld
	Level spawn location: World: (154,68,200), Chunk: (at 10,4,8 in 9,12; contains blocks 144,0,192 to 159,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 33194000 game time, 869308 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 6000 (now: true), thunder time: 6000 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.handler$bih000$modifiedRunLoop(MinecraftServer.java:6810)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.18.0-305.3.1.el8.x86_64
	Java Version: 1.8.0_282, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 745398888 bytes (710 MB) / 2932342784 bytes (2796 MB) up to 59876311040 bytes (57102 MB)
	CPUs: 12
	JVM Flags: 2 total; -Xms128M -Xmx64240M
	Fabric Mods: 
		adventure-platform-fabric: adventure-platform-fabric 4.0.0-SNAPSHOT
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		architectury: Architectury 1.9.136
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		bed_stability: Bed Stability 1.0.0
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.1.1
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		carpet: Carpet Mod 1.4.42
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.19
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		customspawns: Custom Spawns 0.2
		dataloader: Data Loader 2.1.0+mc1.16.1
		fabric: Fabric API 0.37.2+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+6aebe11a7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+95b14da07d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+5badb62d7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+f941baf07d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.4+5badb62d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+6afaa13c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+5f6b94517d
		fabrichomes: FabricHomes 1.0.0
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fastfurnace: FastFurnace 2.4
		flan: Flan 1.16.5-1.6.2
		golfiv: Golf IV 0.3.1
		impersonate: Impersonate 2.2.1
		invview: InvView 1.4.1-1.16.4+
		java: OpenJDK 64-Bit Server VM 8
		krypton: Krypton 0.1.2
		lithium: Lithium 0.6.4
		minecraft: Minecraft 1.16.5
		minimotd-fabric: MiniMOTD 2.0.2
		more_codecs: More Codecs 0.1.2
		mostructures: Mo' Structures 1.2.0-1.16.5
		multi_item_lib: Multi Item Lib 1.3.0
		net_kyori_adventure-api: adventure-api 4.7.0
		net_kyori_adventure-key: adventure-key 4.7.0
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.1.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.7.0
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.7.0
		net_kyori_examination-api: examination-api 1.1.0
		net_kyori_examination-string: examination-string 1.1.0
		netherite_plus: Netherite Plus Mod 1.4.5-1.16.5
		netherroof: NetherRoofMod 1.0.0
		omega-config: OmegaConfig 1.0.4
		org_apache_logging_log4j_log4j-slf4j-impl: log4j-slf4j-impl 2.8.1
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		origins: Origins 0.7.0
		origins-classes: Origins: Classes 1.1.1
		oro_config: OroArmor Config 3.0.0
		paxi: Paxi 1.16.5-1.0
		pehkui: Pehkui 2.0.0+21w14a
		phosphor: Phosphor 0.7.2+build.12
		placeholder-api: Fabric Placeholder API 0.3.0
		player_roles: Player Roles 1.3.1
		randompatches: RandomPatches 2.4.5-fabric
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.5-1.11.6-fabric
		smoothboot: Smooth Boot 1.16.5-1.6.0
		spark: spark 1.6.0
		styledplayerlist: Styled Player List 1.2.1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		traverse: Traverse 3.3.3
		voyager: Voyager 1.0.0
		wires: Wires 1.0.2
		worldedit: WorldEdit 7.2.5+57d5ac9
		yungsapi: YUNG's API 1.16.5-Fabric-8
	Player Count: 2 / 50; [class_3222['W1nterSeal'/42, l='ServerLevel[world]', x=-546.18, y=73.00, z=-445.39], class_3222['TGrag'/150, l='ServerLevel[world]', x=68889.40, y=63.00, z=41958.51]]
	Data Packs: vanilla, Fabric Mods, file/crafting (incompatible), file/merchantnope, file/the_peacekeeper_v2 (incompatible), file/combatlogging, file/upgraded 1.4
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Flemmli97** [comment]
does it happens with only flan installed?

**Comment by ThebigTijn** [comment]
Yes it happends when i try to add a potion effect to a claim. via the /flan menu

**Comment by Flemmli97** [comment]
with just flan and no other mods?

**Comment by ThebigTijn** [comment]
i dont have any other mods that use gui's or any kind of potion effect so i dont think that matters

**Comment by Flemmli97** [comment]
try with no other mods

**Comment by Flemmli97** [comment]
reopen if issue persist
