### ISSUE TITLE
/flan teleport doesnt work for other players who has permissions

### ISSUE THREAD

**Issue by CatbotBox** [Flemmli97/Flan#97]
**Issue :**
* when the other player types ```/flan teleport self``` the available claim name preview also doesn't appear, only the claims owned by that player
typing `/flan teleport self <ClaimName>` would result in no error messages but also no feedback such as the "*Teleporting to claim home. Don't move for 5 seconds*" message
* This is also the same when enabling teleport to a claim in the global permissions menu
* This does work when the the player being teleported is the owner of the claim

**Steps to reproduce:**
1. have 2 players (player 1 and player 2)
2. (player 1) make a claim
3. (player 1) add a player 2 to a permission group and allow teleporting to claim in the permissions.
4. (player 2) use the `/flan setHome` command.
5. (player 2) use the the `/flan teleport self <ClaimName>` command

**Other Mods** :
* N/A

**Comment by Flemmli97** [comment]
intended. self is for your own claims. regardless of permissions. other is for other players
otherwise would need to check for every claim the permission everytime the command is used
